"""Shared fixtures for the tests/test_sync_*.py split (agent-dotfiles#331).

Split out of the former tests/test_sync.py (2969 lines) so each topic file
imports only the fixtures it needs. Pure reorganisation -- no behaviour
change from the original module.
"""

from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

import sync  # noqa: E402

APM_MARKER = "<!-- Generated by APM CLI from .apm/ primitives -->"

# Synthetic manifest, same shape as the real one that surfaced #14:
# one inline `path:`, one bare string item (no `path:` key at all),
# one `path:` value wrapped onto the next line (apm's own emitter
# does this for long paths), and one current, valid entry. Shared between
# GlobalManifestParsingTests (test_sync_stale_global_registration.py) and
# BasenameCollisionTests (test_sync_basename_collision.py) so the fixture
# has one source instead of drifting copies (#331).
SYNTHETIC_GLOBAL_MANIFEST = (
    "name: example-user\n"
    "version: 1.0.0\n"
    "description: APM project for example-user\n"
    "author: Example User\n"
    "dependencies:\n"
    "  apm:\n"
    "    - path: /home/example/projects/skills-checkout\n"
    "      skills:\n"
    "        - az-devops\n"
    "        - create-skill\n"
    "        - failing-test-first\n"
    "        - gh-cli\n"
    "        - github-cli\n"
    "        - linear\n"
    "        - memory-conventions\n"
    "        - obsidian\n"
    "        - safe-deletion\n"
    "        - sanity-check\n"
    "        - tmux\n"
    "        - using-tmux\n"
    "    - /tmp/build-a1b2c3d4/repo\n"
    "    - path: \n"
    "        /tmp/scratchpad/example-issue/repo-bad-private-ref\n"
    "      skills:\n"
    "        - create-skill\n"
    "        - failing-test-first\n"
    "        - github-cli\n"
    "        - linear\n"
    "        - memory-conventions\n"
    "        - obsidian\n"
    "        - safe-deletion\n"
    "        - tmux\n"
    "    - path: /home/example/projects/agent-dotfiles\n"
    "      skills:\n"
    "        - create-skill\n"
    "        - failing-test-first\n"
    "        - github-cli\n"
    "        - linear\n"
    "        - memory-conventions\n"
    "        - obsidian\n"
    "        - safe-deletion\n"
    "        - tmux\n"
    "  mcp: []\n"
    "includes: auto\n"
    "scripts: {}\n"
)


def make_repo(root: Path) -> Path:
    repo = root / "repo"
    (repo / "instructions" / "overlays").mkdir(parents=True)
    (repo / "apm.yml").write_text("name: agent-dotfiles\nversion: 0.1.0\n")
    (repo / "instructions" / "global.instructions.md").write_text(
        "---\ndescription: test\n---\n\n# Global\n\ncore rules\n",
        encoding="utf-8",
    )
    (repo / "instructions" / "overlays" / "pi.md").write_text(
        "# Pi Overlay\n\npi rules\n", encoding="utf-8"
    )
    (repo / "settings" / "claude").mkdir(parents=True)
    (repo / "settings" / "pi").mkdir(parents=True)
    (repo / "settings" / "default-skills.txt").write_text(
        "github-cli\nmemory-conventions\n", encoding="utf-8"
    )
    (repo / "settings" / "claude" / "settings.json").write_text("{}\n")
    (repo / "settings" / "pi" / "settings.json").write_text("{}\n")
    (repo / "settings" / "copilot").mkdir(parents=True)
    (repo / "settings" / "copilot" / "settings.json").write_text("{}\n")
    (repo / "settings" / "mcp").mkdir(parents=True)
    (repo / "settings" / "mcp" / "servers.json").write_text(
        json.dumps({"mcpServers": {}}) + "\n"
    )
    (repo / "hooks").mkdir(parents=True)
    hook = repo / "hooks" / "no-coauthor-trailer"
    hook.write_text(
        "#!/bin/sh\n"
        "grep -Ei '^co-authored-by:' \"$1\" >/dev/null 2>&1 && exit 1\n"
        "exit 0\n",
        encoding="utf-8",
    )
    hook.chmod(0o755)
    return repo


class SyncTestCase(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)
        self.home = self.root / "home"
        self.home.mkdir()
        self.repo = make_repo(self.root)
        self.syncer = sync.Sync(repo_root=self.repo, home=self.home)

    def tearDown(self) -> None:
        self._tmp.cleanup()
