"""Tests for detecting duplicate/foreign compiled root source blocks.

Split out of the former tests/test_sync.py (2969 lines, agent-dotfiles#331).
Pure reorganisation -- no behaviour change.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import tomllib
import unittest
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

import sync  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))

from sync_helpers import APM_MARKER, SyncTestCase, make_repo  # noqa: E402


class CompiledRootSourceBlockTests(SyncTestCase):
    """#14: detect duplicate or foreign `apm:source` blocks in a compiled
    root file. This is the marker convention apm's *legacy* Copilot
    surface (`copilot-instructions.md`) uses -- `<!-- Generated by APM
    CLI -->` (APM_MARKER, checked elsewhere) never appears in it at all.
    The fixture below is the literal shape captured from the real,
    contaminated ~/.copilot/copilot-instructions.md during the #11
    incident (content bodies shortened; the marker structure is verbatim)."""

    def _block(self, source: str, body: str = "content\n") -> str:
        return f"<!-- apm:source:{source} -->\n{body}<!-- /apm:source -->\n"

    def test_no_source_blocks_is_not_a_finding(self) -> None:
        # CLAUDE.md / codex AGENTS.md / copilot AGENTS.md use the other
        # marker convention entirely and never carry apm:source at all.
        path = self.home / ".claude" / "CLAUDE.md"
        path.parent.mkdir(parents=True)
        path.write_text("<!-- Generated by APM CLI from .apm/ primitives -->\nbody\n")
        self.assertEqual(self.syncer.compiled_root_source_findings(path), [])

    def test_one_correctly_named_block_is_not_a_finding(self) -> None:
        path = self.home / ".copilot" / "copilot-instructions.md"
        path.parent.mkdir(parents=True)
        path.write_text(
            "<!-- apm-managed: copilot-instructions.md -->\n"
            + self._block(f"_local/{self.repo.name}")
        )
        self.assertEqual(self.syncer.compiled_root_source_findings(path), [])

    def test_one_foreign_block_is_flagged(self) -> None:
        path = self.home / ".copilot" / "copilot-instructions.md"
        path.parent.mkdir(parents=True)
        path.write_text(
            "<!-- apm-managed: copilot-instructions.md -->\n"
            + self._block("_local/Skills")
        )
        findings = self.syncer.compiled_root_source_findings(path)
        self.assertTrue(findings)
        self.assertTrue(any("_local/Skills" in f for f in findings))

    def test_real_contaminated_shape_reports_duplicate_and_foreign(self) -> None:
        # verbatim marker structure from the real #11 incident file
        path = self.home / ".copilot" / "copilot-instructions.md"
        path.parent.mkdir(parents=True)
        path.write_text(
            "<!-- apm-managed: copilot-instructions.md -->\n"
            + self._block("_local/Skills")
            + self._block("_local/repo-bad-private-ref")
            + self._block("_local/repo-without-vendored-skills")
            + self._block(f"_local/{self.repo.name}")
        )
        findings = self.syncer.compiled_root_source_findings(path)
        self.assertTrue(any("4" in f and "expected 1" in f for f in findings))
        foreign_finding = next(f for f in findings if "foreign" in f)
        reported = [
            name.strip()
            for name in foreign_finding.split(":", 1)[1].split(",")
        ]
        self.assertEqual(
            reported,
            ["_local/Skills", "_local/repo-bad-private-ref", "_local/repo-without-vendored-skills"],
        )
        # the one genuinely-current source is not reported as foreign
        self.assertNotIn(f"_local/{self.repo.name}", reported)

    def test_missing_file_is_not_a_finding(self) -> None:
        path = self.home / ".copilot" / "copilot-instructions.md"
        self.assertEqual(self.syncer.compiled_root_source_findings(path), [])

    def test_status_reports_duplicate_source_blocks_for_copilot_instructions(self) -> None:
        import contextlib
        import io

        path = self.home / ".copilot" / "copilot-instructions.md"
        path.parent.mkdir(parents=True)
        path.write_text(
            "<!-- apm-managed: copilot-instructions.md -->\n"
            + self._block("_local/Skills")
            + self._block(f"_local/{self.repo.name}")
        )
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            rc = self.syncer.status()
        self.assertIn("copilot-instructions.md", buf.getvalue())
        self.assertIn("_local/Skills", buf.getvalue())
        self.assertNotEqual(rc, 0)

    def test_doctor_reports_duplicate_source_blocks(self) -> None:
        path = self.home / ".copilot" / "copilot-instructions.md"
        path.parent.mkdir(parents=True)
        path.write_text(
            "<!-- apm-managed: copilot-instructions.md -->\n"
            + self._block("_local/Skills")
            + self._block(f"_local/{self.repo.name}")
        )
        checks = dict(self.syncer.doctor_checks(env={}))
        self.assertIn("compiled-root-sources", checks)
        ok, message = checks["compiled-root-sources"]
        self.assertFalse(ok)
        self.assertIn("copilot-instructions.md", message)
