"""Tests for the sync wrapper (scripts/sync.py)."""

from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

import sync  # noqa: E402

APM_MARKER = "<!-- Generated by APM CLI from .apm/ primitives -->"


def make_repo(root: Path) -> Path:
    repo = root / "repo"
    (repo / "instructions" / "overlays").mkdir(parents=True)
    (repo / "apm.yml").write_text("name: agent-dotfiles\nversion: 0.1.0\n")
    (repo / "instructions" / "global.instructions.md").write_text(
        "---\ndescription: test\n---\n\n# Global\n\ncore rules\n",
        encoding="utf-8",
    )
    (repo / "instructions" / "overlays" / "pi.md").write_text(
        "# Pi Overlay\n\npi rules\n", encoding="utf-8"
    )
    (repo / "settings" / "claude").mkdir(parents=True)
    (repo / "settings" / "pi").mkdir(parents=True)
    (repo / "settings" / "default-skills.txt").write_text(
        "github-cli\nmemory-conventions\n", encoding="utf-8"
    )
    (repo / "settings" / "claude" / "settings.json").write_text("{}\n")
    (repo / "settings" / "pi" / "settings.json").write_text("{}\n")
    (repo / "settings" / "copilot").mkdir(parents=True)
    (repo / "settings" / "copilot" / "settings.json").write_text("{}\n")
    (repo / "settings" / "mcp").mkdir(parents=True)
    (repo / "settings" / "mcp" / "servers.json").write_text(
        json.dumps({"mcpServers": {}}) + "\n"
    )
    return repo


class SyncTestCase(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)
        self.home = self.root / "home"
        self.home.mkdir()
        self.repo = make_repo(self.root)
        self.syncer = sync.Sync(repo_root=self.repo, home=self.home)

    def tearDown(self) -> None:
        self._tmp.cleanup()


class PiProjectionTests(SyncTestCase):
    def test_initializes_pi_dir_when_binary_on_path(self) -> None:
        self.syncer.pi_available = lambda: True
        self.syncer.project_pi()
        out = self.home / ".pi" / "agent" / "AGENTS.md"
        self.assertTrue(out.is_file())

    def test_apply_creates_neutral_skills_dir(self) -> None:
        self.syncer.apply(no_apm=True)
        self.assertTrue((self.home / ".agents" / "skills").is_dir())

    def test_apply_mirrors_claude_skills_into_empty_neutral_path(self) -> None:
        src = self.home / ".claude" / "skills" / "github-cli"
        src.mkdir(parents=True)
        (src / "SKILL.md").write_text("---\nname: github-cli\n---\nbody\n")
        self.syncer.apply(no_apm=True)
        mirrored = self.home / ".agents" / "skills" / "github-cli"
        self.assertTrue(mirrored.is_symlink() or mirrored.is_dir())
        self.assertTrue((mirrored / "SKILL.md").is_file())

    def test_projects_core_plus_overlay_when_pi_present(self) -> None:
        (self.home / ".pi" / "agent").mkdir(parents=True)
        self.syncer.project_pi()
        out = (self.home / ".pi" / "agent" / "AGENTS.md").read_text()
        self.assertIn(sync.SYNC_MARKER, out)
        self.assertIn("core rules", out)
        self.assertIn("pi rules", out)
        self.assertNotIn("description: test", out)  # frontmatter stripped

    def test_skipped_when_pi_absent(self) -> None:
        self.syncer.pi_available = lambda: False
        self.syncer.project_pi()
        self.assertFalse((self.home / ".pi" / "agent" / "AGENTS.md").exists())

    def test_refuses_to_overwrite_hand_authored_file(self) -> None:
        target = self.home / ".pi" / "agent" / "AGENTS.md"
        target.parent.mkdir(parents=True)
        target.write_text("my own pi instructions\n")
        self.syncer.project_pi()
        self.assertEqual(target.read_text(), "my own pi instructions\n")


class TeardownTests(SyncTestCase):
    def test_removes_only_marker_owned_unused_root_files(self) -> None:
        cursor = self.home / ".cursor" / "AGENTS.md"
        cursor.parent.mkdir(parents=True)
        cursor.write_text(APM_MARKER + "\ngenerated\n")
        gemini = self.home / ".gemini" / "GEMINI.md"
        gemini.parent.mkdir(parents=True)
        gemini.write_text("hand authored\n")
        claude = self.home / ".claude" / "CLAUDE.md"
        claude.parent.mkdir(parents=True)
        claude.write_text(APM_MARKER + "\ngenerated\n")

        removed = self.syncer.teardown_unused_root_files()

        self.assertFalse(cursor.exists())
        self.assertTrue(gemini.exists())  # no marker -> untouched
        self.assertTrue(claude.exists())  # managed harness -> kept
        self.assertIn(cursor, removed)


class SettingsMergeTests(SyncTestCase):
    def test_merge_preserves_unmanaged_keys_and_records_previous(self) -> None:
        fragment = self.repo / "settings" / "claude" / "settings.json"
        fragment.write_text(json.dumps({"model": "opus", "env": {"FOO": "1"}}))
        live = self.home / ".claude" / "settings.json"
        live.parent.mkdir(parents=True)
        live.write_text(json.dumps({"model": "sonnet", "theme": "dark"}))

        self.syncer.merge_settings("claude", live)

        merged = json.loads(live.read_text())
        self.assertEqual(merged["model"], "opus")
        self.assertEqual(merged["theme"], "dark")  # unmanaged key preserved
        self.assertEqual(merged["env"], {"FOO": "1"})
        prev = self.syncer.state["settings"][str(live)]
        self.assertEqual(prev["model"], "sonnet")
        self.assertEqual(prev["env"], sync.ABSENT)

    def test_apply_merges_copilot_fragment_when_harness_present(self) -> None:
        (self.repo / "settings" / "copilot" / "settings.json").write_text(
            json.dumps({"model": "claude-sonnet-5"})
        )
        live = self.home / ".copilot" / "settings.json"
        live.parent.mkdir(parents=True)
        live.write_text(json.dumps({"model": "auto", "theme": "auto"}))
        self.syncer.apply(no_apm=True)
        merged = json.loads(live.read_text())
        self.assertEqual(merged["model"], "claude-sonnet-5")
        self.assertEqual(merged["theme"], "auto")

    def test_empty_fragment_is_noop(self) -> None:
        live = self.home / ".claude" / "settings.json"
        live.parent.mkdir(parents=True)
        live.write_text(json.dumps({"theme": "dark"}))
        self.syncer.merge_settings("claude", live)
        self.assertEqual(json.loads(live.read_text()), {"theme": "dark"})
        self.assertNotIn(str(live), self.syncer.state["settings"])


class McpMergeTests(SyncTestCase):
    def write_fragment(self, servers: dict) -> None:
        (self.repo / "settings" / "mcp" / "servers.json").write_text(
            json.dumps({"mcpServers": servers}) + "\n"
        )

    def test_merge_writes_declared_servers_preserving_unmanaged(self) -> None:
        self.write_fragment(
            {"context7": {"type": "http", "url": "https://c7.example/mcp"}}
        )
        live = self.home / ".claude.json"
        live.write_text(
            json.dumps(
                {
                    "mcpServers": {"personal": {"command": "foo"}},
                    "projects": {"/x": {}},
                }
            )
        )

        self.syncer.merge_mcp()

        merged = json.loads(live.read_text())
        self.assertEqual(
            merged["mcpServers"]["context7"]["url"], "https://c7.example/mcp"
        )
        self.assertEqual(merged["mcpServers"]["personal"], {"command": "foo"})
        self.assertEqual(merged["projects"], {"/x": {}})  # untouched
        prev = self.syncer.state["mcp"][str(live)]
        self.assertEqual(prev["context7"], sync.ABSENT)

    def test_merge_records_previous_value_of_overridden_server(self) -> None:
        self.write_fragment({"context7": {"type": "http", "url": "https://new"}})
        live = self.home / ".claude.json"
        live.write_text(
            json.dumps({"mcpServers": {"context7": {"command": "old"}}})
        )
        self.syncer.merge_mcp()
        prev = self.syncer.state["mcp"][str(live)]
        self.assertEqual(prev["context7"], {"command": "old"})

    def test_merge_creates_live_file_when_absent(self) -> None:
        self.write_fragment({"deepwiki": {"type": "http", "url": "https://dw"}})
        self.syncer.merge_mcp()
        merged = json.loads((self.home / ".claude.json").read_text())
        self.assertEqual(merged["mcpServers"]["deepwiki"]["url"], "https://dw")

    def test_empty_or_missing_fragment_is_noop(self) -> None:
        self.syncer.merge_mcp()
        self.assertFalse((self.home / ".claude.json").exists())
        (self.repo / "settings" / "mcp" / "servers.json").unlink()
        self.syncer.merge_mcp()
        self.assertFalse((self.home / ".claude.json").exists())

    def test_apply_runs_mcp_merge(self) -> None:
        self.write_fragment({"deepwiki": {"type": "http", "url": "https://dw"}})
        self.syncer.apply(no_apm=True)
        merged = json.loads((self.home / ".claude.json").read_text())
        self.assertIn("deepwiki", merged["mcpServers"])

    def test_remove_restores_previous_mcp_state(self) -> None:
        self.write_fragment(
            {
                "context7": {"type": "http", "url": "https://new"},
                "deepwiki": {"type": "http", "url": "https://dw"},
            }
        )
        live = self.home / ".claude.json"
        live.write_text(
            json.dumps(
                {
                    "mcpServers": {
                        "context7": {"command": "old"},
                        "personal": {"command": "foo"},
                    }
                }
            )
        )
        self.syncer.apply(no_apm=True)
        self.syncer.remove(no_apm=True)
        restored = json.loads(live.read_text())
        self.assertEqual(
            restored["mcpServers"],
            {"context7": {"command": "old"}, "personal": {"command": "foo"}},
        )

    def test_apply_twice_then_remove_restores_original(self) -> None:
        self.write_fragment({"deepwiki": {"type": "http", "url": "https://dw"}})
        live = self.home / ".claude.json"
        live.write_text(json.dumps({"mcpServers": {}}))
        self.syncer.apply(no_apm=True)
        self.syncer.apply(no_apm=True)
        self.syncer.remove(no_apm=True)
        self.assertEqual(json.loads(live.read_text()), {"mcpServers": {}})

    def test_doctor_warns_on_unset_mcp_env_var(self) -> None:
        self.write_fragment(
            {
                "context7": {
                    "type": "http",
                    "url": "https://c7",
                    "headers": {"Authorization": "Bearer ${CONTEXT7_API_KEY}"},
                }
            }
        )
        checks = dict(self.syncer.doctor_checks(env={}))
        ok, detail = checks["mcp-env-CONTEXT7_API_KEY"]
        self.assertIsNone(ok)  # warning, not failure
        self.assertIn("CONTEXT7_API_KEY", detail)
        checks = dict(
            self.syncer.doctor_checks(env={"CONTEXT7_API_KEY": "abc"})
        )
        self.assertTrue(checks["mcp-env-CONTEXT7_API_KEY"][0])

    def test_status_flags_declared_server_missing_from_live(self) -> None:
        self.write_fragment({"deepwiki": {"type": "http", "url": "https://dw"}})
        self.syncer.apply(no_apm=True)
        live = self.home / ".claude.json"
        live.write_text(json.dumps({"mcpServers": {}}))
        self.assertEqual(self.syncer.status(), 1)


class CodexMcpTests(SyncTestCase):
    def write_fragment(self, servers: dict) -> None:
        (self.repo / "settings" / "mcp" / "servers.json").write_text(
            json.dumps({"mcpServers": servers}) + "\n"
        )

    def setUp(self) -> None:
        super().setUp()
        self.config = self.home / ".codex" / "config.toml"
        self.config.parent.mkdir()
        self.config.write_text(
            'model = "gpt"\n\n[mcp_servers.node_repl]\ncommand = "node"\n'
        )
        self.write_fragment(
            {
                "context7": {
                    "type": "http",
                    "url": "https://c7.example/mcp",
                    "headers": {"Authorization": "Bearer ${CONTEXT7_API_KEY}"},
                },
                "deepwiki": {"type": "http", "url": "https://dw.example/mcp"},
            }
        )

    def test_writes_marker_block_preserving_existing_config(self) -> None:
        self.syncer.merge_codex_mcp()
        text = self.config.read_text()
        self.assertIn('model = "gpt"', text)
        self.assertIn("[mcp_servers.node_repl]", text)
        self.assertIn(sync.CODEX_MCP_BEGIN, text)
        self.assertIn("[mcp_servers.context7]", text)
        self.assertIn('url = "https://c7.example/mcp"', text)
        self.assertIn('bearer_token_env_var = "CONTEXT7_API_KEY"', text)
        self.assertIn("[mcp_servers.deepwiki]", text)
        self.assertIn(sync.CODEX_MCP_END, text)

    def test_idempotent_reapply_keeps_single_block(self) -> None:
        self.syncer.merge_codex_mcp()
        first = self.config.read_text()
        self.syncer.merge_codex_mcp()
        self.assertEqual(self.config.read_text(), first)

    def test_skips_server_already_defined_outside_block(self) -> None:
        self.config.write_text(
            'model = "gpt"\n\n[mcp_servers.context7]\ncommand = "mine"\n'
        )
        self.syncer.merge_codex_mcp()
        text = self.config.read_text()
        self.assertEqual(text.count("[mcp_servers.context7]"), 1)
        self.assertIn('command = "mine"', text)
        self.assertIn("[mcp_servers.deepwiki]", text)  # others still land

    def test_skipped_when_codex_absent(self) -> None:
        self.config.unlink()
        self.config.parent.rmdir()
        self.syncer.merge_codex_mcp()
        self.assertFalse(self.config.exists())

    def test_remove_strips_block_only(self) -> None:
        self.syncer.merge_codex_mcp()
        self.syncer.save_state()
        self.syncer.remove(no_apm=True)
        text = self.config.read_text()
        self.assertIn('model = "gpt"', text)
        self.assertIn("[mcp_servers.node_repl]", text)
        self.assertNotIn(sync.CODEX_MCP_BEGIN, text)
        self.assertNotIn("context7", text)


class CopilotMcpTests(SyncTestCase):
    def write_fragment(self, servers: dict) -> None:
        (self.repo / "settings" / "mcp" / "servers.json").write_text(
            json.dumps({"mcpServers": servers}) + "\n"
        )

    def setUp(self) -> None:
        super().setUp()
        (self.home / ".copilot").mkdir()
        self.mcp_config = self.home / ".copilot" / "mcp-config.json"
        self.write_fragment(
            {"deepwiki": {"type": "http", "url": "https://dw.example/mcp"}}
        )

    def test_merge_creates_mcp_config_preserving_unmanaged(self) -> None:
        self.mcp_config.write_text(
            json.dumps({"mcpServers": {"personal": {"command": "foo"}}})
        )
        self.syncer.merge_copilot_mcp()
        merged = json.loads(self.mcp_config.read_text())
        self.assertEqual(
            merged["mcpServers"]["deepwiki"]["url"], "https://dw.example/mcp"
        )
        self.assertEqual(merged["mcpServers"]["personal"], {"command": "foo"})

    def test_skipped_when_copilot_absent(self) -> None:
        (self.home / ".copilot").rmdir()
        self.syncer.merge_copilot_mcp()
        self.assertFalse(self.mcp_config.exists())

    def test_remove_restores_previous(self) -> None:
        self.syncer.apply(no_apm=True)
        self.assertTrue(self.mcp_config.is_file())
        self.syncer.remove(no_apm=True)
        merged = json.loads(self.mcp_config.read_text())
        self.assertNotIn("deepwiki", merged["mcpServers"])

    def test_status_flags_missing_copilot_server(self) -> None:
        self.syncer.apply(no_apm=True)
        self.mcp_config.write_text(json.dumps({"mcpServers": {}}))
        self.assertEqual(self.syncer.status(), 1)


class RemoveTests(SyncTestCase):
    def test_remove_restores_settings_and_deletes_projection(self) -> None:
        (self.home / ".pi" / "agent").mkdir(parents=True)
        fragment = self.repo / "settings" / "claude" / "settings.json"
        fragment.write_text(json.dumps({"model": "opus"}))
        live = self.home / ".claude" / "settings.json"
        live.parent.mkdir(parents=True)
        live.write_text(json.dumps({"model": "sonnet", "theme": "dark"}))

        self.syncer.apply(no_apm=True)
        self.syncer.remove(no_apm=True)

        self.assertFalse((self.home / ".pi" / "agent" / "AGENTS.md").exists())
        restored = json.loads(live.read_text())
        self.assertEqual(restored, {"model": "sonnet", "theme": "dark"})

    def test_apply_twice_then_remove_is_clean(self) -> None:
        (self.home / ".pi" / "agent").mkdir(parents=True)
        self.syncer.apply(no_apm=True)
        first = (self.home / ".pi" / "agent" / "AGENTS.md").read_text()
        self.syncer.apply(no_apm=True)
        self.assertEqual(
            (self.home / ".pi" / "agent" / "AGENTS.md").read_text(), first
        )
        self.syncer.remove(no_apm=True)
        self.assertFalse((self.home / ".pi" / "agent" / "AGENTS.md").exists())


class StatusTests(SyncTestCase):
    def test_status_skips_uninstalled_harnesses(self) -> None:
        # no harness dirs exist in the fresh fake home
        self.assertEqual(self.syncer.status(), 0)

    def test_status_flags_missing_file_when_harness_present(self) -> None:
        (self.home / ".claude").mkdir()
        self.assertEqual(self.syncer.status(), 1)


class ApplyOrderTests(SyncTestCase):
    def test_apply_pins_the_default_skill_roster(self) -> None:
        calls = []

        def runner(cmd, check=False):
            calls.append(cmd)

            class R:
                returncode = 0

            return R()

        self.syncer.runner = runner
        self.assertEqual(self.syncer.apply(), 0)
        self.assertEqual(
            calls[0],
            [
                "apm",
                "install",
                "-g",
                str(self.repo),
                "--skill",
                "github-cli",
                "--skill",
                "memory-conventions",
            ],
        )

    def test_apply_forces_marker_owned_roots_to_recompile(self) -> None:
        claude = self.home / ".claude" / "CLAUDE.md"
        claude.parent.mkdir(parents=True)
        claude.write_text(APM_MARKER + "\nstale rules\n")
        saw_missing_before_compile = False

        def runner(cmd, check=False):
            nonlocal saw_missing_before_compile
            if cmd[1] == "compile":
                saw_missing_before_compile = not claude.exists()
                claude.write_text(APM_MARKER + "\ncurrent rules\n")

            class R:
                returncode = 0

            return R()

        self.syncer.runner = runner
        self.assertEqual(self.syncer.apply(), 0)
        self.assertTrue(saw_missing_before_compile)
        self.assertIn("current rules", claude.read_text())

    def test_apply_preserves_last_good_root_when_compile_skips_it(self) -> None:
        claude = self.home / ".claude" / "CLAUDE.md"
        claude.parent.mkdir(parents=True)
        original = APM_MARKER + "\nlast known good\n"
        claude.write_text(original)

        def runner(cmd, check=False):
            class R:
                returncode = 0

            return R()

        self.syncer.runner = runner
        self.assertEqual(self.syncer.apply(), 0)
        self.assertEqual(claude.read_text(), original)

    def test_apply_runs_install_then_compile_then_teardown(self) -> None:
        calls = []
        home = self.home

        def runner(cmd, check=False):
            calls.append(cmd[1])
            if cmd[1] == "compile":
                stale = home / ".cursor" / "AGENTS.md"
                stale.parent.mkdir(parents=True, exist_ok=True)
                stale.write_text(APM_MARKER + "\ngenerated\n")

            class R:
                returncode = 0

            return R()

        self.syncer.runner = runner
        self.assertEqual(self.syncer.apply(), 0)
        self.assertEqual(calls[:2], ["install", "compile"])
        # teardown must run AFTER compile: the stale root compile wrote is gone
        self.assertFalse((home / ".cursor" / "AGENTS.md").exists())

    def test_apply_aborts_when_compile_fails(self) -> None:
        calls = []
        claude = self.home / ".claude" / "CLAUDE.md"
        claude.parent.mkdir(parents=True)
        original = APM_MARKER + "\nlast known good\n"
        claude.write_text(original)

        def runner(cmd, check=False):
            calls.append(cmd[1])

            class R:
                returncode = 7 if cmd[1] == "compile" else 0

            return R()

        self.syncer.runner = runner
        self.assertEqual(self.syncer.apply(), 7)
        self.assertEqual(calls, ["install", "compile"])
        self.assertEqual(claude.read_text(), original)
        self.assertFalse(self.syncer.state_file.exists())


class DoctorTests(SyncTestCase):
    def test_flags_corporate_memory_vault(self) -> None:
        env = {
            "AGENT_MEMORY_VAULT": str(
                self.home / "Library/CloudStorage/OneDrive-Gentiva/vault"
            )
        }
        checks = dict(self.syncer.doctor_checks(env=env))
        self.assertFalse(checks["memory-vault-personal"][0])

    def test_accepts_personal_vault(self) -> None:
        vault = self.home / "Library/CloudStorage/OneDrive-Personal/vault"
        vault.mkdir(parents=True)
        env = {"AGENT_MEMORY_VAULT": str(vault)}
        checks = dict(self.syncer.doctor_checks(env=env))
        self.assertTrue(checks["memory-vault-personal"][0])

    def test_vault_set_but_missing_path_fails(self) -> None:
        env = {"AGENT_MEMORY_VAULT": str(self.home / "no-such-vault")}
        checks = dict(self.syncer.doctor_checks(env=env))
        ok, detail = checks["memory-vault-personal"]
        self.assertFalse(ok)
        self.assertIn("does not exist", detail)

    def test_accepts_existing_personal_vault_with_agent_dir(self) -> None:
        vault = self.home / "icloud" / "Agent Memory"
        (vault / "agent" / "facts").mkdir(parents=True)
        (vault / "agent" / "index.md").write_text("# idx\n")
        env = {"AGENT_MEMORY_VAULT": str(vault)}
        checks = dict(self.syncer.doctor_checks(env=env))
        self.assertTrue(checks["memory-vault-personal"][0])

    def test_missing_claude_harness_is_warning_not_failure(self) -> None:
        checks = dict(self.syncer.doctor_checks(env={}))
        ok, detail = checks["claude-root-file"]
        self.assertIsNone(ok)
        self.assertIn("not installed", detail)

    def test_codex_and_copilot_root_files_checked_when_installed(self) -> None:
        for harness in (".codex", ".copilot"):
            (self.home / harness).mkdir()
        checks = dict(self.syncer.doctor_checks(env={}))
        self.assertFalse(checks["codex-root-file"][0])  # dir, no root file
        self.assertFalse(checks["copilot-root-file"][0])
        (self.home / ".codex" / "AGENTS.md").write_text(APM_MARKER + "\nx\n")
        (self.home / ".copilot" / "AGENTS.md").write_text(APM_MARKER + "\nx\n")
        checks = dict(self.syncer.doctor_checks(env={}))
        self.assertTrue(checks["codex-root-file"][0])
        self.assertTrue(checks["copilot-root-file"][0])

    def test_codex_copilot_absent_is_warning(self) -> None:
        checks = dict(self.syncer.doctor_checks(env={}))
        self.assertIsNone(checks["codex-root-file"][0])
        self.assertIsNone(checks["copilot-root-file"][0])

    def test_unset_vault_is_warning_not_failure(self) -> None:
        checks = dict(self.syncer.doctor_checks(env={}))
        ok, detail = checks["memory-vault-personal"]
        self.assertIsNone(ok)  # None = warning
        self.assertIn("not set", detail)


if __name__ == "__main__":
    unittest.main()


class SkillRosterScopingTests(SyncTestCase):
    """SPEC §4.1 — per-harness roster sections, Tier A neutral scoping."""

    SECTIONED = (
        "# shared roster (all harnesses)\n"
        "github-cli\n"
        "memory-conventions\n"
        "\n"
        "[copilot]\n"
        "safe-deletion\n"
        "\n"
        "[codex]\n"
        "tmux\n"
    )

    def write_roster(self, text: str) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            text, encoding="utf-8"
        )

    def test_flat_roster_stays_valid_and_is_shared_by_every_harness(self) -> None:
        self.write_roster("github-cli\nmemory-conventions\n")
        shared = sync.load_default_skills(self.repo)
        self.assertEqual(shared, ["github-cli", "memory-conventions"])
        for harness in ("claude", "pi", "codex", "copilot"):
            self.assertEqual(
                sync.load_default_skills(self.repo, harness), shared
            )

    def test_named_harness_gets_shared_plus_its_section(self) -> None:
        self.write_roster(self.SECTIONED)
        self.assertEqual(
            sync.load_default_skills(self.repo),
            ["github-cli", "memory-conventions"],
        )
        self.assertEqual(
            sync.load_default_skills(self.repo, "copilot"),
            ["github-cli", "memory-conventions", "safe-deletion"],
        )
        self.assertEqual(
            sync.load_default_skills(self.repo, "codex"),
            ["github-cli", "memory-conventions", "tmux"],
        )
        self.assertEqual(
            sync.load_default_skills(self.repo, "claude"),
            ["github-cli", "memory-conventions"],
        )

    def test_union_covers_every_section_for_apm_install(self) -> None:
        self.write_roster(self.SECTIONED)
        self.assertEqual(
            sync.roster_union(self.repo),
            ["github-cli", "memory-conventions", "safe-deletion", "tmux"],
        )

    def test_neutral_union_excludes_claude_only_skills(self) -> None:
        self.write_roster(self.SECTIONED + "\n[claude]\nprimer\n")
        self.assertEqual(
            sync.neutral_union(self.repo),
            ["github-cli", "memory-conventions", "safe-deletion", "tmux"],
        )

    # -- Tier A mirroring ------------------------------------------------

    def seed_claude_skills(self, *names: str) -> Path:
        claude = self.home / ".claude" / "skills"
        claude.mkdir(parents=True, exist_ok=True)
        for name in names:
            (claude / name).mkdir(exist_ok=True)
        return claude

    def test_mirrors_only_the_neutral_union(self) -> None:
        self.write_roster(self.SECTIONED + "\n[claude]\nprimer\n")
        self.seed_claude_skills(
            "github-cli", "memory-conventions", "safe-deletion", "tmux", "primer"
        )
        self.syncer.ensure_neutral_skills()
        neutral = self.home / ".agents" / "skills"
        self.assertEqual(
            sorted(p.name for p in neutral.iterdir()),
            ["github-cli", "memory-conventions", "safe-deletion", "tmux"],
        )
        self.assertFalse((neutral / "primer").exists())

    def test_removing_from_a_section_removes_the_wrapper_symlink(self) -> None:
        self.write_roster(self.SECTIONED)
        self.seed_claude_skills(
            "github-cli", "memory-conventions", "safe-deletion", "tmux"
        )
        self.syncer.ensure_neutral_skills()
        neutral = self.home / ".agents" / "skills"
        self.assertTrue((neutral / "safe-deletion").is_symlink())

        # drop the [copilot] section entirely
        self.write_roster("github-cli\nmemory-conventions\n\n[codex]\ntmux\n")
        self.syncer.ensure_neutral_skills()
        self.assertFalse((neutral / "safe-deletion").exists())
        self.assertTrue((neutral / "tmux").is_symlink())

    def test_never_removes_a_link_the_wrapper_did_not_create(self) -> None:
        self.write_roster("github-cli\n")
        self.seed_claude_skills("github-cli", "hand-made")
        neutral = self.home / ".agents" / "skills"
        neutral.mkdir(parents=True, exist_ok=True)
        (neutral / "hand-made").symlink_to(self.home / ".claude" / "skills" / "hand-made")
        self.syncer.ensure_neutral_skills()
        self.assertTrue(
            (neutral / "hand-made").exists(),
            "unmanaged links must survive — removal is state-tracked",
        )

    def test_removal_is_recorded_in_state_and_reversible(self) -> None:
        self.write_roster(self.SECTIONED)
        self.seed_claude_skills(
            "github-cli", "memory-conventions", "safe-deletion", "tmux"
        )
        self.syncer.ensure_neutral_skills()
        self.assertIn(
            "safe-deletion", self.syncer.state.get("neutral_skills", [])
        )
        self.write_roster("github-cli\nmemory-conventions\n\n[codex]\ntmux\n")
        self.syncer.ensure_neutral_skills()
        self.assertNotIn(
            "safe-deletion", self.syncer.state.get("neutral_skills", [])
        )
        # restoring the section restores the link
        self.write_roster(self.SECTIONED)
        self.syncer.ensure_neutral_skills()
        self.assertTrue(
            (self.home / ".agents" / "skills" / "safe-deletion").is_symlink()
        )


class RosterReportingTests(SyncTestCase):
    """SPEC §4.1 — status reports resolved rosters; doctor flags drift."""

    def setUp(self) -> None:
        super().setUp()
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n\n[copilot]\nsafe-deletion\n", encoding="utf-8"
        )

    def test_resolved_rosters_are_reported(self) -> None:
        report = self.syncer.roster_report()
        self.assertEqual(report["claude"], ["github-cli"])
        self.assertEqual(report["copilot"], ["github-cli", "safe-deletion"])
        self.assertEqual(report["pi"], ["github-cli"])

    def test_doctor_flags_neutral_path_drift(self) -> None:
        claude = self.home / ".claude" / "skills"
        claude.mkdir(parents=True)
        (claude / "github-cli").mkdir()
        neutral = self.home / ".agents" / "skills"
        neutral.mkdir(parents=True)
        # a link the wrapper recorded, for a skill no longer in any roster
        (neutral / "stale-skill").symlink_to(claude / "github-cli")
        self.syncer.state["neutral_skills"] = ["stale-skill"]
        names = dict(self.syncer.doctor_checks({}))
        self.assertIn("neutral-roster-drift", names)
        self.assertFalse(names["neutral-roster-drift"][0])

    def test_doctor_passes_when_neutral_path_matches(self) -> None:
        claude = self.home / ".claude" / "skills"
        claude.mkdir(parents=True)
        for name in ("github-cli", "safe-deletion"):
            (claude / name).mkdir()
        self.syncer.ensure_neutral_skills()
        names = dict(self.syncer.doctor_checks({}))
        self.assertNotEqual(names["neutral-roster-drift"][0], False)


class PreexistingNeutralLinkTests(SyncTestCase):
    """Links from the pre-§4.1 wholesale mirroring are untracked, so they
    cannot be auto-removed — doctor must surface them instead of leaving a
    scoped skill silently readable on the shared path."""

    def test_untracked_out_of_union_link_is_reported_not_deleted(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n\n[claude]\nprimer\n", encoding="utf-8"
        )
        claude = self.home / ".claude" / "skills"
        claude.mkdir(parents=True)
        for name in ("github-cli", "primer"):
            (claude / name).mkdir()
        neutral = self.home / ".agents" / "skills"
        neutral.mkdir(parents=True)
        # what the old wholesale mirror left behind
        (neutral / "primer").symlink_to(claude / "primer")

        self.syncer.ensure_neutral_skills()
        self.assertTrue(
            (neutral / "primer").exists(), "untracked links are never deleted"
        )
        names = dict(self.syncer.doctor_checks({}))
        check = names["neutral-roster-drift"]
        self.assertFalse(check[0])
        self.assertIn("primer", check[1])


class ClaudeSkillOverrideTests(SyncTestCase):
    """APM installs the union into ~/.claude/skills, so a skill scoped away
    from Claude Code still reaches it. V9 resolved the Tier B lever
    (`skillOverrides`); the wrapper derives it from the roster so the two
    cannot drift."""

    def test_skills_excluded_from_claude_are_turned_off(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n\n[codex]\nsanity-check\n\n[pi]\nsanity-check\n", encoding="utf-8"
        )
        self.assertEqual(sync.claude_skill_overrides(self.repo), {"sanity-check": "off"})

    def test_flat_roster_produces_no_overrides(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\nmemory-conventions\n", encoding="utf-8"
        )
        self.assertEqual(sync.claude_skill_overrides(self.repo), {})

    def test_claude_scoped_skills_are_not_turned_off(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n\n[claude]\nprimer\n", encoding="utf-8"
        )
        self.assertEqual(sync.claude_skill_overrides(self.repo), {})


class NameOnlyRosterTests(SyncTestCase):
    """`name-only` is the third roster state SPEC §4.1 names and #96 asked
    for: keep the skill invocable, stop paying for its description. It is a
    modifier on membership, not an exclusion — so a `@name-only` skill stays
    in the resolved roster and is still deployed."""

    def roster(self, text: str) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(text, encoding="utf-8")

    def test_modifier_is_stripped_from_the_resolved_roster(self) -> None:
        self.roster("github-cli\nobsidian @name-only\n")
        self.assertEqual(
            sync.load_default_skills(self.repo), ["github-cli", "obsidian"]
        )

    def test_name_only_skill_is_still_installed(self) -> None:
        """The whole point: it stays deployed and invocable."""
        self.roster("github-cli\nobsidian @name-only\n")
        self.assertIn("obsidian", sync.roster_union(self.repo))
        self.assertIn("obsidian", sync.neutral_union(self.repo))

    def test_override_is_name_only_not_off(self) -> None:
        self.roster("github-cli\nobsidian @name-only\n")
        self.assertEqual(
            sync.claude_skill_overrides(self.repo), {"obsidian": "name-only"}
        )

    def test_name_only_and_off_coexist(self) -> None:
        """A skill scoped away from Claude is still `off`; the modifier only
        changes skills Claude keeps."""
        self.roster("github-cli\nobsidian @name-only\n\n[codex]\nsanity-check\n")
        self.assertEqual(
            sync.claude_skill_overrides(self.repo),
            {"obsidian": "name-only", "sanity-check": "off"},
        )

    def test_modifier_applies_inside_a_harness_section(self) -> None:
        self.roster("github-cli\n\n[claude]\nprimer @name-only\n")
        self.assertEqual(
            sync.claude_skill_overrides(self.repo), {"primer": "name-only"}
        )

    def test_unknown_modifier_is_refused_rather_than_ignored(self) -> None:
        """Silently dropping an unrecognised modifier would deploy a roster
        that does not match what the file asks for."""
        self.roster("github-cli\nobsidian @nmae-only\n")
        with self.assertRaises(ValueError) as caught:
            sync.load_skill_roster(self.repo)
        self.assertIn("@nmae-only", str(caught.exception))

    def test_skill_modifiers_reports_only_annotated_skills(self) -> None:
        self.roster("github-cli\nobsidian @name-only\n")
        self.assertEqual(sync.skill_modifiers(self.repo), {"obsidian": "name-only"})


class CopilotDisabledSkillsTests(SyncTestCase):
    """Copilot reads the shared ~/.agents/skills directory, so a skill scoped
    to Codex and Pi reaches Copilot too. V10 resolved affirmatively on
    2026-07-27 — `disabledSkills` in ~/.copilot/settings.json, verified live —
    and it is derived from the roster for the same reason Claude Code's is."""

    def test_skills_excluded_from_copilot_are_disabled(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n\n[codex]\nsanity-check\n\n[pi]\nsanity-check\n", encoding="utf-8"
        )
        self.assertEqual(sync.copilot_disabled_skills(self.repo), ["sanity-check"])

    def test_flat_roster_disables_nothing(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\nmemory-conventions\n", encoding="utf-8"
        )
        self.assertEqual(sync.copilot_disabled_skills(self.repo), [])

    def test_copilot_scoped_skills_are_not_disabled(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n\n[copilot]\nsanity-check\n", encoding="utf-8"
        )
        self.assertEqual(sync.copilot_disabled_skills(self.repo), [])


class CodexSkillDisableTests(SyncTestCase):
    """Codex's Tier B lever is `[[skills.config]]` with `enabled = false` in
    ~/.codex/config.toml, keyed by the bare skill name for personal skills
    (plugin skills are namespaced, e.g. `github:yeet`). Verified live on
    2026-07-27: a fresh `codex exec` stopped listing the disabled skill."""

    def test_excluded_skills_render_as_disabled_entries(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n\n[pi]\nsanity-check\n", encoding="utf-8"
        )
        self.assertEqual(sync.codex_disabled_skills(self.repo), ["sanity-check"])

    def test_codex_scoped_skills_are_not_disabled(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n\n[codex]\nsanity-check\n", encoding="utf-8"
        )
        self.assertEqual(sync.codex_disabled_skills(self.repo), [])

    def test_block_is_written_and_leaves_foreign_entries_alone(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n\n[pi]\nsanity-check\n", encoding="utf-8"
        )
        codex = self.home / ".codex"
        codex.mkdir(parents=True, exist_ok=True)
        config = codex / "config.toml"
        config.write_text(
            '[[skills.config]]\nname = "github:yeet"\nenabled = false\n',
            encoding="utf-8",
        )
        sync.Sync(self.repo, self.home).merge_codex_skills()
        text = config.read_text(encoding="utf-8")
        self.assertIn('name = "sanity-check"', text)
        self.assertIn('name = "github:yeet"', text)  # user's own entry survives
        self.assertIn(sync.CODEX_SKILLS_BEGIN, text)

    def test_block_is_removed_when_nothing_is_excluded(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n\n[pi]\nsanity-check\n", encoding="utf-8"
        )
        codex = self.home / ".codex"
        codex.mkdir(parents=True, exist_ok=True)
        s = sync.Sync(self.repo, self.home)
        s.merge_codex_skills()
        self.assertIn("sanity-check", (codex / "config.toml").read_text(encoding="utf-8"))
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\nsanity-check\n", encoding="utf-8"
        )
        sync.Sync(self.repo, self.home).merge_codex_skills()
        self.assertNotIn("sanity-check", (codex / "config.toml").read_text(encoding="utf-8"))


class PiSkillDenylistTests(SyncTestCase):
    """Pi's Tier B lever is a `skills` denylist in ~/.pi/agent/settings.json,
    whose entries are paths: `-skills/<name>/SKILL.md`."""

    def test_excluded_skills_become_denylist_paths(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n\n[codex]\nsanity-check\n", encoding="utf-8"
        )
        self.assertEqual(
            sync.pi_disabled_skills(self.repo), ["-skills/sanity-check/SKILL.md"]
        )

    def test_pi_scoped_skills_are_not_denied(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n\n[pi]\nsanity-check\n", encoding="utf-8"
        )
        self.assertEqual(sync.pi_disabled_skills(self.repo), [])


class HarnessOverlayTests(SyncTestCase):
    """Per-harness instruction overlays existed only for Pi, so a sentence
    needed by one harness was billed to all four — E17's cost 48 tokens on
    every column when only Copilot failed the scenario (#85)."""

    def _overlay(self, name: str, body: str) -> None:
        d = self.repo / "instructions" / "overlays"
        d.mkdir(parents=True, exist_ok=True)
        (d / f"{name}.md").write_text(body, encoding="utf-8")

    def _root(self, harness: str) -> Path:
        first = None
        for rel in sync.HARNESS_ROOT_FILES[harness]:
            path = self.home / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text("# canonical\n\ncore instructions\n", encoding="utf-8")
            first = first or path
        return first

    def test_overlay_is_appended_to_the_harness_root(self) -> None:
        root = self._root("copilot")
        self._overlay("copilot", "# Copilot Overlay\n\nagreement is not evidence.\n")
        sync.Sync(self.repo, self.home).apply_overlays()
        text = root.read_text(encoding="utf-8")
        self.assertIn("core instructions", text)
        self.assertIn("agreement is not evidence.", text)
        self.assertIn(sync.OVERLAY_BEGIN, text)

    def test_reapply_does_not_duplicate(self) -> None:
        root = self._root("copilot")
        self._overlay("copilot", "# Copilot Overlay\n\nonce.\n")
        for _ in range(3):
            sync.Sync(self.repo, self.home).apply_overlays()
        self.assertEqual(root.read_text(encoding="utf-8").count("once."), 1)

    def test_emptied_overlay_removes_the_block(self) -> None:
        root = self._root("copilot")
        self._overlay("copilot", "# Copilot Overlay\n\ntemporary.\n")
        sync.Sync(self.repo, self.home).apply_overlays()
        self._overlay("copilot", "# Copilot Overlay\n\nIntentionally empty.\n")
        sync.Sync(self.repo, self.home).apply_overlays()
        text = root.read_text(encoding="utf-8")
        self.assertNotIn("temporary.", text)
        self.assertNotIn(sync.OVERLAY_BEGIN, text)
        self.assertIn("core instructions", text)

    def test_placeholder_overlay_writes_nothing(self) -> None:
        """claude-code.md documents itself as intentionally empty; that must
        not produce a block."""
        root = self._root("claude")
        self._overlay("claude-code", "# Claude Code Overlay\n\nIntentionally empty. Native norms cover it.\n")
        sync.Sync(self.repo, self.home).apply_overlays()
        self.assertNotIn(sync.OVERLAY_BEGIN, root.read_text(encoding="utf-8"))

    def test_missing_harness_directory_is_skipped(self) -> None:
        self._overlay("copilot", "# Copilot Overlay\n\nsomething.\n")
        sync.Sync(self.repo, self.home).apply_overlays()  # must not raise


class OverlayBodyTests(SyncTestCase):
    """An overlay file documents why its rule exists; the harness should be
    charged only for the rule. The E17 overlay's rationale added ~45 tokens
    to Copilot's static context before comments were stripped (2026-07-27)."""

    def _write(self, body: str) -> None:
        d = self.repo / "instructions" / "overlays"
        d.mkdir(parents=True, exist_ok=True)
        (d / "copilot.md").write_text(body, encoding="utf-8")

    def test_html_comments_are_not_projected(self) -> None:
        self._write(
            "# Copilot Overlay\n\nThe rule.\n\n"
            "<!--\nWhy: measured on E17, Copilot only.\n-->\n"
        )
        body = sync.overlay_body(self.repo, "copilot")
        self.assertIn("The rule.", body)
        self.assertNotIn("Why:", body)
        self.assertNotIn("<!--", body)

    def test_an_overlay_that_is_only_a_comment_projects_nothing(self) -> None:
        self._write("# Copilot Overlay\n\n<!--\nNotes for maintainers.\n-->\n")
        self.assertEqual(sync.overlay_body(self.repo, "copilot"), "")


class CopilotBothInstructionFilesTests(SyncTestCase):
    """Copilot reads ~/.copilot/copilot-instructions.md, not AGENTS.md.

    The overlay was written to AGENTS.md alone on 2026-07-27 and was never in
    context: asked directly, a fresh Copilot answered "NO — my instructions
    don't contain a rule stating that agreement between dispatched agents
    isn't evidence", while quoting a rule that lives in the other file. Four
    eval runs referenced the policy zero times and nearly became a finding
    about delivery surfaces."""

    def test_overlay_reaches_every_file_the_harness_reads(self) -> None:
        d = self.repo / "instructions" / "overlays"
        d.mkdir(parents=True, exist_ok=True)
        (d / "copilot.md").write_text("# Copilot Overlay\n\nthe rule.\n", encoding="utf-8")
        copilot = self.home / ".copilot"
        copilot.mkdir(parents=True)
        for name in ("AGENTS.md", "copilot-instructions.md"):
            (copilot / name).write_text("core\n", encoding="utf-8")
        sync.Sync(self.repo, self.home).apply_overlays()
        for name in ("AGENTS.md", "copilot-instructions.md"):
            self.assertIn("the rule.", (copilot / name).read_text(encoding="utf-8"),
                          f"{name} missing the overlay")


class ForeignSettingsEntryTests(SyncTestCase):
    """`deep_merge` recurses into dicts but replaces lists wholesale, so a
    list-valued managed key loses anything the wrapper did not write. Hit for
    real on 2026-07-29: removing a stale disable entry while its skill was
    still deployed made the skill load on four harnesses instead of two."""

    def _fragment(self, harness: str, body: dict) -> None:
        d = self.repo / "settings" / harness
        d.mkdir(parents=True, exist_ok=True)
        (d / "settings.json").write_text(json.dumps(body), encoding="utf-8")

    def test_apply_keeps_a_foreign_disabled_skill_entry(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n\n[codex]\nsanity-check\n", encoding="utf-8"
        )
        live = self.home / ".copilot" / "settings.json"
        live.parent.mkdir(parents=True, exist_ok=True)
        live.write_text(
            json.dumps({"disabledSkills": ["vendor-thing"]}), encoding="utf-8"
        )
        self._fragment("copilot", {})
        sync.Sync(self.repo, self.home).merge_settings("copilot", live)
        entries = json.loads(live.read_text())["disabledSkills"]
        self.assertIn("vendor-thing", entries, "foreign entry was deleted")
        self.assertIn("sanity-check", entries, "derived entry missing")

    def test_remove_restores_foreign_entries_rather_than_dropping_the_key(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n\n[codex]\nsanity-check\n", encoding="utf-8"
        )
        live = self.home / ".copilot" / "settings.json"
        live.parent.mkdir(parents=True, exist_ok=True)
        live.write_text(
            json.dumps({"disabledSkills": ["vendor-thing"]}), encoding="utf-8"
        )
        self._fragment("copilot", {})
        s = sync.Sync(self.repo, self.home)
        s.merge_settings("copilot", live)
        s.restore_settings(live)
        entries = json.loads(live.read_text()).get("disabledSkills", [])
        self.assertEqual(entries, ["vendor-thing"], "foreign entry not restored")


class ListOwnershipTests(SyncTestCase):
    """The wrapper must withdraw its own stale entries while leaving foreign
    ones. Union alone leaves residue; replacement alone deletes other
    people's entries. Both failure modes were hit on 2026-07-29."""

    def _roster(self, body: str) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(body, encoding="utf-8")

    def _live(self) -> Path:
        p = self.home / ".copilot" / "settings.json"
        p.parent.mkdir(parents=True, exist_ok=True)
        return p

    def test_stale_wrapper_entry_is_withdrawn_when_the_roster_changes(self) -> None:
        live = self._live()
        live.write_text("{}", encoding="utf-8")
        (self.repo / "settings" / "copilot").mkdir(parents=True, exist_ok=True)
        (self.repo / "settings" / "copilot" / "settings.json").write_text("{}", encoding="utf-8")

        self._roster("github-cli\n\n[codex]\nsanity-check\n")
        s = sync.Sync(self.repo, self.home)
        s.merge_settings("copilot", live)
        self.assertEqual(json.loads(live.read_text())["disabledSkills"], ["sanity-check"])

        # sanity-check leaves the roster entirely — its disable must go too
        self._roster("github-cli\nsanity-check\n")
        s.merge_settings("copilot", live)
        self.assertEqual(json.loads(live.read_text()).get("disabledSkills"), [])

    def test_foreign_entry_survives_a_roster_change(self) -> None:
        live = self._live()
        live.write_text(json.dumps({"disabledSkills": ["vendor-thing"]}), encoding="utf-8")
        (self.repo / "settings" / "copilot").mkdir(parents=True, exist_ok=True)
        (self.repo / "settings" / "copilot" / "settings.json").write_text("{}", encoding="utf-8")

        self._roster("github-cli\n\n[codex]\nsanity-check\n")
        s = sync.Sync(self.repo, self.home)
        s.merge_settings("copilot", live)
        self._roster("github-cli\nsanity-check\n")
        s.merge_settings("copilot", live)
        self.assertEqual(json.loads(live.read_text())["disabledSkills"], ["vendor-thing"])


class SharedPathIdentityTests(SyncTestCase):
    """`doctor` passed by comparing names, and the wrapper owns nothing on the
    shared path, so a foreign skill installed under a managed name would be
    loaded by Codex, Copilot and Pi with every check green (#93).

    Identity is checked on the description rather than the whole file: APM
    rewrites relative links in the body when it installs, so byte-comparison
    reports a false mismatch on a legitimately deployed skill."""

    def _deploy(self, name: str, description: str) -> None:
        d = self.home / ".agents" / "skills" / name
        d.mkdir(parents=True, exist_ok=True)
        (d / "SKILL.md").write_text(
            f"---\nname: {name}\ndescription: {description}\n---\n\nbody\n",
            encoding="utf-8",
        )

    def _source(self, name: str, description: str, body: str = "body") -> None:
        d = self.repo / "skills" / name
        d.mkdir(parents=True, exist_ok=True)
        (d / "SKILL.md").write_text(
            f"---\nname: {name}\ndescription: {description}\n---\n\n{body}\n",
            encoding="utf-8",
        )

    def test_substituted_skill_is_reported(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n", encoding="utf-8"
        )
        self._source("github-cli", "Manage GitHub via CLI.")
        self._deploy("github-cli", "Totally different thing from elsewhere.")
        mismatches = sync.Sync(self.repo, self.home).neutral_identity()
        self.assertEqual(mismatches, ["github-cli"])

    def test_matching_deployment_is_silent(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n", encoding="utf-8"
        )
        self._source("github-cli", "Manage GitHub via CLI.")
        self._deploy("github-cli", "Manage GitHub via CLI.")
        self.assertEqual(sync.Sync(self.repo, self.home).neutral_identity(), [])

    def test_body_differences_do_not_trip_it(self) -> None:
        """APM rewrites relative links on install; that is not substitution."""
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n", encoding="utf-8"
        )
        self._source("github-cli", "Manage GitHub via CLI.", body="see [x](../y.md)")
        self._deploy("github-cli", "Manage GitHub via CLI.")
        self.assertEqual(sync.Sync(self.repo, self.home).neutral_identity(), [])

    def test_absent_skill_is_not_a_mismatch(self) -> None:
        (self.repo / "settings" / "default-skills.txt").write_text(
            "github-cli\n", encoding="utf-8"
        )
        self._source("github-cli", "Manage GitHub via CLI.")
        self.assertEqual(sync.Sync(self.repo, self.home).neutral_identity(), [])
