"""Tests for the sync wrapper (scripts/sync.py)."""

from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

import sync  # noqa: E402

APM_MARKER = "<!-- Generated by APM CLI from .apm/ primitives -->"


def make_repo(root: Path) -> Path:
    repo = root / "repo"
    (repo / "instructions" / "overlays").mkdir(parents=True)
    (repo / "apm.yml").write_text("name: agent-dotfiles\nversion: 0.1.0\n")
    (repo / "instructions" / "global.instructions.md").write_text(
        "---\ndescription: test\n---\n\n# Global\n\ncore rules\n",
        encoding="utf-8",
    )
    (repo / "instructions" / "overlays" / "pi.md").write_text(
        "# Pi Overlay\n\npi rules\n", encoding="utf-8"
    )
    (repo / "settings" / "claude").mkdir(parents=True)
    (repo / "settings" / "pi").mkdir(parents=True)
    (repo / "settings" / "claude" / "settings.json").write_text("{}\n")
    (repo / "settings" / "pi" / "settings.json").write_text("{}\n")
    return repo


class SyncTestCase(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)
        self.home = self.root / "home"
        self.home.mkdir()
        self.repo = make_repo(self.root)
        self.syncer = sync.Sync(repo_root=self.repo, home=self.home)

    def tearDown(self) -> None:
        self._tmp.cleanup()


class PiProjectionTests(SyncTestCase):
    def test_projects_core_plus_overlay_when_pi_present(self) -> None:
        (self.home / ".pi" / "agent").mkdir(parents=True)
        self.syncer.project_pi()
        out = (self.home / ".pi" / "agent" / "AGENTS.md").read_text()
        self.assertIn(sync.SYNC_MARKER, out)
        self.assertIn("core rules", out)
        self.assertIn("pi rules", out)
        self.assertNotIn("description: test", out)  # frontmatter stripped

    def test_skipped_when_pi_absent(self) -> None:
        self.syncer.project_pi()
        self.assertFalse((self.home / ".pi" / "agent" / "AGENTS.md").exists())

    def test_refuses_to_overwrite_hand_authored_file(self) -> None:
        target = self.home / ".pi" / "agent" / "AGENTS.md"
        target.parent.mkdir(parents=True)
        target.write_text("my own pi instructions\n")
        self.syncer.project_pi()
        self.assertEqual(target.read_text(), "my own pi instructions\n")


class TeardownTests(SyncTestCase):
    def test_removes_only_marker_owned_unused_root_files(self) -> None:
        cursor = self.home / ".cursor" / "AGENTS.md"
        cursor.parent.mkdir(parents=True)
        cursor.write_text(APM_MARKER + "\ngenerated\n")
        gemini = self.home / ".gemini" / "GEMINI.md"
        gemini.parent.mkdir(parents=True)
        gemini.write_text("hand authored\n")
        claude = self.home / ".claude" / "CLAUDE.md"
        claude.parent.mkdir(parents=True)
        claude.write_text(APM_MARKER + "\ngenerated\n")

        removed = self.syncer.teardown_unused_root_files()

        self.assertFalse(cursor.exists())
        self.assertTrue(gemini.exists())  # no marker -> untouched
        self.assertTrue(claude.exists())  # managed harness -> kept
        self.assertIn(cursor, removed)


class SettingsMergeTests(SyncTestCase):
    def test_merge_preserves_unmanaged_keys_and_records_previous(self) -> None:
        fragment = self.repo / "settings" / "claude" / "settings.json"
        fragment.write_text(json.dumps({"model": "opus", "env": {"FOO": "1"}}))
        live = self.home / ".claude" / "settings.json"
        live.parent.mkdir(parents=True)
        live.write_text(json.dumps({"model": "sonnet", "theme": "dark"}))

        self.syncer.merge_settings("claude", live)

        merged = json.loads(live.read_text())
        self.assertEqual(merged["model"], "opus")
        self.assertEqual(merged["theme"], "dark")  # unmanaged key preserved
        self.assertEqual(merged["env"], {"FOO": "1"})
        prev = self.syncer.state["settings"][str(live)]
        self.assertEqual(prev["model"], "sonnet")
        self.assertEqual(prev["env"], sync.ABSENT)

    def test_empty_fragment_is_noop(self) -> None:
        live = self.home / ".claude" / "settings.json"
        live.parent.mkdir(parents=True)
        live.write_text(json.dumps({"theme": "dark"}))
        self.syncer.merge_settings("claude", live)
        self.assertEqual(json.loads(live.read_text()), {"theme": "dark"})
        self.assertNotIn(str(live), self.syncer.state["settings"])


class RemoveTests(SyncTestCase):
    def test_remove_restores_settings_and_deletes_projection(self) -> None:
        (self.home / ".pi" / "agent").mkdir(parents=True)
        fragment = self.repo / "settings" / "claude" / "settings.json"
        fragment.write_text(json.dumps({"model": "opus"}))
        live = self.home / ".claude" / "settings.json"
        live.parent.mkdir(parents=True)
        live.write_text(json.dumps({"model": "sonnet", "theme": "dark"}))

        self.syncer.apply(no_apm=True)
        self.syncer.remove(no_apm=True)

        self.assertFalse((self.home / ".pi" / "agent" / "AGENTS.md").exists())
        restored = json.loads(live.read_text())
        self.assertEqual(restored, {"model": "sonnet", "theme": "dark"})

    def test_apply_twice_then_remove_is_clean(self) -> None:
        (self.home / ".pi" / "agent").mkdir(parents=True)
        self.syncer.apply(no_apm=True)
        first = (self.home / ".pi" / "agent" / "AGENTS.md").read_text()
        self.syncer.apply(no_apm=True)
        self.assertEqual(
            (self.home / ".pi" / "agent" / "AGENTS.md").read_text(), first
        )
        self.syncer.remove(no_apm=True)
        self.assertFalse((self.home / ".pi" / "agent" / "AGENTS.md").exists())


class DoctorTests(SyncTestCase):
    def test_flags_corporate_memory_vault(self) -> None:
        env = {
            "AGENT_MEMORY_VAULT": str(
                self.home / "Library/CloudStorage/OneDrive-Gentiva/vault"
            )
        }
        checks = dict(self.syncer.doctor_checks(env=env))
        self.assertFalse(checks["memory-vault-personal"][0])

    def test_accepts_personal_vault(self) -> None:
        env = {
            "AGENT_MEMORY_VAULT": str(
                self.home / "Library/CloudStorage/OneDrive-Personal/vault"
            )
        }
        checks = dict(self.syncer.doctor_checks(env=env))
        self.assertTrue(checks["memory-vault-personal"][0])

    def test_unset_vault_is_warning_not_failure(self) -> None:
        checks = dict(self.syncer.doctor_checks(env={}))
        ok, detail = checks["memory-vault-personal"]
        self.assertIsNone(ok)  # None = warning
        self.assertIn("not set", detail)


if __name__ == "__main__":
    unittest.main()
