"""Tests for the sync wrapper (scripts/sync.py)."""

from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

import sync  # noqa: E402

APM_MARKER = "<!-- Generated by APM CLI from .apm/ primitives -->"


def make_repo(root: Path) -> Path:
    repo = root / "repo"
    (repo / "instructions" / "overlays").mkdir(parents=True)
    (repo / "apm.yml").write_text("name: agent-dotfiles\nversion: 0.1.0\n")
    (repo / "instructions" / "global.instructions.md").write_text(
        "---\ndescription: test\n---\n\n# Global\n\ncore rules\n",
        encoding="utf-8",
    )
    (repo / "instructions" / "overlays" / "pi.md").write_text(
        "# Pi Overlay\n\npi rules\n", encoding="utf-8"
    )
    (repo / "settings" / "claude").mkdir(parents=True)
    (repo / "settings" / "pi").mkdir(parents=True)
    (repo / "settings" / "default-skills.txt").write_text(
        "gh-cli\nmemory-conventions\n", encoding="utf-8"
    )
    (repo / "settings" / "claude" / "settings.json").write_text("{}\n")
    (repo / "settings" / "pi" / "settings.json").write_text("{}\n")
    (repo / "settings" / "mcp").mkdir(parents=True)
    (repo / "settings" / "mcp" / "servers.json").write_text(
        json.dumps({"mcpServers": {}}) + "\n"
    )
    return repo


class SyncTestCase(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)
        self.home = self.root / "home"
        self.home.mkdir()
        self.repo = make_repo(self.root)
        self.syncer = sync.Sync(repo_root=self.repo, home=self.home)

    def tearDown(self) -> None:
        self._tmp.cleanup()


class PiProjectionTests(SyncTestCase):
    def test_initializes_pi_dir_when_binary_on_path(self) -> None:
        self.syncer.pi_available = lambda: True
        self.syncer.project_pi()
        out = self.home / ".pi" / "agent" / "AGENTS.md"
        self.assertTrue(out.is_file())

    def test_apply_creates_neutral_skills_dir(self) -> None:
        self.syncer.apply(no_apm=True)
        self.assertTrue((self.home / ".agents" / "skills").is_dir())

    def test_apply_mirrors_claude_skills_into_empty_neutral_path(self) -> None:
        src = self.home / ".claude" / "skills" / "gh-cli"
        src.mkdir(parents=True)
        (src / "SKILL.md").write_text("---\nname: gh-cli\n---\nbody\n")
        self.syncer.apply(no_apm=True)
        mirrored = self.home / ".agents" / "skills" / "gh-cli"
        self.assertTrue(mirrored.is_symlink() or mirrored.is_dir())
        self.assertTrue((mirrored / "SKILL.md").is_file())

    def test_projects_core_plus_overlay_when_pi_present(self) -> None:
        (self.home / ".pi" / "agent").mkdir(parents=True)
        self.syncer.project_pi()
        out = (self.home / ".pi" / "agent" / "AGENTS.md").read_text()
        self.assertIn(sync.SYNC_MARKER, out)
        self.assertIn("core rules", out)
        self.assertIn("pi rules", out)
        self.assertNotIn("description: test", out)  # frontmatter stripped

    def test_skipped_when_pi_absent(self) -> None:
        self.syncer.pi_available = lambda: False
        self.syncer.project_pi()
        self.assertFalse((self.home / ".pi" / "agent" / "AGENTS.md").exists())

    def test_refuses_to_overwrite_hand_authored_file(self) -> None:
        target = self.home / ".pi" / "agent" / "AGENTS.md"
        target.parent.mkdir(parents=True)
        target.write_text("my own pi instructions\n")
        self.syncer.project_pi()
        self.assertEqual(target.read_text(), "my own pi instructions\n")


class TeardownTests(SyncTestCase):
    def test_removes_only_marker_owned_unused_root_files(self) -> None:
        cursor = self.home / ".cursor" / "AGENTS.md"
        cursor.parent.mkdir(parents=True)
        cursor.write_text(APM_MARKER + "\ngenerated\n")
        gemini = self.home / ".gemini" / "GEMINI.md"
        gemini.parent.mkdir(parents=True)
        gemini.write_text("hand authored\n")
        claude = self.home / ".claude" / "CLAUDE.md"
        claude.parent.mkdir(parents=True)
        claude.write_text(APM_MARKER + "\ngenerated\n")

        removed = self.syncer.teardown_unused_root_files()

        self.assertFalse(cursor.exists())
        self.assertTrue(gemini.exists())  # no marker -> untouched
        self.assertTrue(claude.exists())  # managed harness -> kept
        self.assertIn(cursor, removed)


class SettingsMergeTests(SyncTestCase):
    def test_merge_preserves_unmanaged_keys_and_records_previous(self) -> None:
        fragment = self.repo / "settings" / "claude" / "settings.json"
        fragment.write_text(json.dumps({"model": "opus", "env": {"FOO": "1"}}))
        live = self.home / ".claude" / "settings.json"
        live.parent.mkdir(parents=True)
        live.write_text(json.dumps({"model": "sonnet", "theme": "dark"}))

        self.syncer.merge_settings("claude", live)

        merged = json.loads(live.read_text())
        self.assertEqual(merged["model"], "opus")
        self.assertEqual(merged["theme"], "dark")  # unmanaged key preserved
        self.assertEqual(merged["env"], {"FOO": "1"})
        prev = self.syncer.state["settings"][str(live)]
        self.assertEqual(prev["model"], "sonnet")
        self.assertEqual(prev["env"], sync.ABSENT)

    def test_empty_fragment_is_noop(self) -> None:
        live = self.home / ".claude" / "settings.json"
        live.parent.mkdir(parents=True)
        live.write_text(json.dumps({"theme": "dark"}))
        self.syncer.merge_settings("claude", live)
        self.assertEqual(json.loads(live.read_text()), {"theme": "dark"})
        self.assertNotIn(str(live), self.syncer.state["settings"])


class McpMergeTests(SyncTestCase):
    def write_fragment(self, servers: dict) -> None:
        (self.repo / "settings" / "mcp" / "servers.json").write_text(
            json.dumps({"mcpServers": servers}) + "\n"
        )

    def test_merge_writes_declared_servers_preserving_unmanaged(self) -> None:
        self.write_fragment(
            {"context7": {"type": "http", "url": "https://c7.example/mcp"}}
        )
        live = self.home / ".claude.json"
        live.write_text(
            json.dumps(
                {
                    "mcpServers": {"personal": {"command": "foo"}},
                    "projects": {"/x": {}},
                }
            )
        )

        self.syncer.merge_mcp()

        merged = json.loads(live.read_text())
        self.assertEqual(
            merged["mcpServers"]["context7"]["url"], "https://c7.example/mcp"
        )
        self.assertEqual(merged["mcpServers"]["personal"], {"command": "foo"})
        self.assertEqual(merged["projects"], {"/x": {}})  # untouched
        prev = self.syncer.state["mcp"][str(live)]
        self.assertEqual(prev["context7"], sync.ABSENT)

    def test_merge_records_previous_value_of_overridden_server(self) -> None:
        self.write_fragment({"context7": {"type": "http", "url": "https://new"}})
        live = self.home / ".claude.json"
        live.write_text(
            json.dumps({"mcpServers": {"context7": {"command": "old"}}})
        )
        self.syncer.merge_mcp()
        prev = self.syncer.state["mcp"][str(live)]
        self.assertEqual(prev["context7"], {"command": "old"})

    def test_merge_creates_live_file_when_absent(self) -> None:
        self.write_fragment({"deepwiki": {"type": "http", "url": "https://dw"}})
        self.syncer.merge_mcp()
        merged = json.loads((self.home / ".claude.json").read_text())
        self.assertEqual(merged["mcpServers"]["deepwiki"]["url"], "https://dw")

    def test_empty_or_missing_fragment_is_noop(self) -> None:
        self.syncer.merge_mcp()
        self.assertFalse((self.home / ".claude.json").exists())
        (self.repo / "settings" / "mcp" / "servers.json").unlink()
        self.syncer.merge_mcp()
        self.assertFalse((self.home / ".claude.json").exists())

    def test_apply_runs_mcp_merge(self) -> None:
        self.write_fragment({"deepwiki": {"type": "http", "url": "https://dw"}})
        self.syncer.apply(no_apm=True)
        merged = json.loads((self.home / ".claude.json").read_text())
        self.assertIn("deepwiki", merged["mcpServers"])

    def test_remove_restores_previous_mcp_state(self) -> None:
        self.write_fragment(
            {
                "context7": {"type": "http", "url": "https://new"},
                "deepwiki": {"type": "http", "url": "https://dw"},
            }
        )
        live = self.home / ".claude.json"
        live.write_text(
            json.dumps(
                {
                    "mcpServers": {
                        "context7": {"command": "old"},
                        "personal": {"command": "foo"},
                    }
                }
            )
        )
        self.syncer.apply(no_apm=True)
        self.syncer.remove(no_apm=True)
        restored = json.loads(live.read_text())
        self.assertEqual(
            restored["mcpServers"],
            {"context7": {"command": "old"}, "personal": {"command": "foo"}},
        )

    def test_apply_twice_then_remove_restores_original(self) -> None:
        self.write_fragment({"deepwiki": {"type": "http", "url": "https://dw"}})
        live = self.home / ".claude.json"
        live.write_text(json.dumps({"mcpServers": {}}))
        self.syncer.apply(no_apm=True)
        self.syncer.apply(no_apm=True)
        self.syncer.remove(no_apm=True)
        self.assertEqual(json.loads(live.read_text()), {"mcpServers": {}})

    def test_doctor_warns_on_unset_mcp_env_var(self) -> None:
        self.write_fragment(
            {
                "context7": {
                    "type": "http",
                    "url": "https://c7",
                    "headers": {"Authorization": "Bearer ${CONTEXT7_API_KEY}"},
                }
            }
        )
        checks = dict(self.syncer.doctor_checks(env={}))
        ok, detail = checks["mcp-env-CONTEXT7_API_KEY"]
        self.assertIsNone(ok)  # warning, not failure
        self.assertIn("CONTEXT7_API_KEY", detail)
        checks = dict(
            self.syncer.doctor_checks(env={"CONTEXT7_API_KEY": "abc"})
        )
        self.assertTrue(checks["mcp-env-CONTEXT7_API_KEY"][0])

    def test_status_flags_declared_server_missing_from_live(self) -> None:
        self.write_fragment({"deepwiki": {"type": "http", "url": "https://dw"}})
        self.syncer.apply(no_apm=True)
        live = self.home / ".claude.json"
        live.write_text(json.dumps({"mcpServers": {}}))
        self.assertEqual(self.syncer.status(), 1)


class RemoveTests(SyncTestCase):
    def test_remove_restores_settings_and_deletes_projection(self) -> None:
        (self.home / ".pi" / "agent").mkdir(parents=True)
        fragment = self.repo / "settings" / "claude" / "settings.json"
        fragment.write_text(json.dumps({"model": "opus"}))
        live = self.home / ".claude" / "settings.json"
        live.parent.mkdir(parents=True)
        live.write_text(json.dumps({"model": "sonnet", "theme": "dark"}))

        self.syncer.apply(no_apm=True)
        self.syncer.remove(no_apm=True)

        self.assertFalse((self.home / ".pi" / "agent" / "AGENTS.md").exists())
        restored = json.loads(live.read_text())
        self.assertEqual(restored, {"model": "sonnet", "theme": "dark"})

    def test_apply_twice_then_remove_is_clean(self) -> None:
        (self.home / ".pi" / "agent").mkdir(parents=True)
        self.syncer.apply(no_apm=True)
        first = (self.home / ".pi" / "agent" / "AGENTS.md").read_text()
        self.syncer.apply(no_apm=True)
        self.assertEqual(
            (self.home / ".pi" / "agent" / "AGENTS.md").read_text(), first
        )
        self.syncer.remove(no_apm=True)
        self.assertFalse((self.home / ".pi" / "agent" / "AGENTS.md").exists())


class StatusTests(SyncTestCase):
    def test_status_skips_uninstalled_harnesses(self) -> None:
        # no harness dirs exist in the fresh fake home
        self.assertEqual(self.syncer.status(), 0)

    def test_status_flags_missing_file_when_harness_present(self) -> None:
        (self.home / ".claude").mkdir()
        self.assertEqual(self.syncer.status(), 1)


class ApplyOrderTests(SyncTestCase):
    def test_apply_pins_the_default_skill_roster(self) -> None:
        calls = []

        def runner(cmd, check=False):
            calls.append(cmd)

            class R:
                returncode = 0

            return R()

        self.syncer.runner = runner
        self.assertEqual(self.syncer.apply(), 0)
        self.assertEqual(
            calls[0],
            [
                "apm",
                "install",
                "-g",
                str(self.repo),
                "--skill",
                "gh-cli",
                "--skill",
                "memory-conventions",
            ],
        )

    def test_apply_forces_marker_owned_roots_to_recompile(self) -> None:
        claude = self.home / ".claude" / "CLAUDE.md"
        claude.parent.mkdir(parents=True)
        claude.write_text(APM_MARKER + "\nstale rules\n")
        saw_missing_before_compile = False

        def runner(cmd, check=False):
            nonlocal saw_missing_before_compile
            if cmd[1] == "compile":
                saw_missing_before_compile = not claude.exists()
                claude.write_text(APM_MARKER + "\ncurrent rules\n")

            class R:
                returncode = 0

            return R()

        self.syncer.runner = runner
        self.assertEqual(self.syncer.apply(), 0)
        self.assertTrue(saw_missing_before_compile)
        self.assertIn("current rules", claude.read_text())

    def test_apply_preserves_last_good_root_when_compile_skips_it(self) -> None:
        claude = self.home / ".claude" / "CLAUDE.md"
        claude.parent.mkdir(parents=True)
        original = APM_MARKER + "\nlast known good\n"
        claude.write_text(original)

        def runner(cmd, check=False):
            class R:
                returncode = 0

            return R()

        self.syncer.runner = runner
        self.assertEqual(self.syncer.apply(), 0)
        self.assertEqual(claude.read_text(), original)

    def test_apply_runs_install_then_compile_then_teardown(self) -> None:
        calls = []
        home = self.home

        def runner(cmd, check=False):
            calls.append(cmd[1])
            if cmd[1] == "compile":
                stale = home / ".cursor" / "AGENTS.md"
                stale.parent.mkdir(parents=True, exist_ok=True)
                stale.write_text(APM_MARKER + "\ngenerated\n")

            class R:
                returncode = 0

            return R()

        self.syncer.runner = runner
        self.assertEqual(self.syncer.apply(), 0)
        self.assertEqual(calls[:2], ["install", "compile"])
        # teardown must run AFTER compile: the stale root compile wrote is gone
        self.assertFalse((home / ".cursor" / "AGENTS.md").exists())

    def test_apply_aborts_when_compile_fails(self) -> None:
        calls = []
        claude = self.home / ".claude" / "CLAUDE.md"
        claude.parent.mkdir(parents=True)
        original = APM_MARKER + "\nlast known good\n"
        claude.write_text(original)

        def runner(cmd, check=False):
            calls.append(cmd[1])

            class R:
                returncode = 7 if cmd[1] == "compile" else 0

            return R()

        self.syncer.runner = runner
        self.assertEqual(self.syncer.apply(), 7)
        self.assertEqual(calls, ["install", "compile"])
        self.assertEqual(claude.read_text(), original)
        self.assertFalse(self.syncer.state_file.exists())


class DoctorTests(SyncTestCase):
    def test_flags_corporate_memory_vault(self) -> None:
        env = {
            "AGENT_MEMORY_VAULT": str(
                self.home / "Library/CloudStorage/OneDrive-Gentiva/vault"
            )
        }
        checks = dict(self.syncer.doctor_checks(env=env))
        self.assertFalse(checks["memory-vault-personal"][0])

    def test_accepts_personal_vault(self) -> None:
        vault = self.home / "Library/CloudStorage/OneDrive-Personal/vault"
        vault.mkdir(parents=True)
        env = {"AGENT_MEMORY_VAULT": str(vault)}
        checks = dict(self.syncer.doctor_checks(env=env))
        self.assertTrue(checks["memory-vault-personal"][0])

    def test_vault_set_but_missing_path_fails(self) -> None:
        env = {"AGENT_MEMORY_VAULT": str(self.home / "no-such-vault")}
        checks = dict(self.syncer.doctor_checks(env=env))
        ok, detail = checks["memory-vault-personal"]
        self.assertFalse(ok)
        self.assertIn("does not exist", detail)

    def test_accepts_existing_personal_vault_with_agent_dir(self) -> None:
        vault = self.home / "icloud" / "Agent Memory"
        (vault / "agent" / "facts").mkdir(parents=True)
        (vault / "agent" / "index.md").write_text("# idx\n")
        env = {"AGENT_MEMORY_VAULT": str(vault)}
        checks = dict(self.syncer.doctor_checks(env=env))
        self.assertTrue(checks["memory-vault-personal"][0])

    def test_missing_claude_harness_is_warning_not_failure(self) -> None:
        checks = dict(self.syncer.doctor_checks(env={}))
        ok, detail = checks["claude-root-file"]
        self.assertIsNone(ok)
        self.assertIn("not installed", detail)

    def test_unset_vault_is_warning_not_failure(self) -> None:
        checks = dict(self.syncer.doctor_checks(env={}))
        ok, detail = checks["memory-vault-personal"]
        self.assertIsNone(ok)  # None = warning
        self.assertIn("not set", detail)


if __name__ == "__main__":
    unittest.main()
