#!/usr/bin/env python3
"""Refresh tests/fixtures/known_references.txt from GitHub.

Maintenance tool, not part of CI. tests/test_cross_repo_references.py must
run offline, so it checks bare '#N' citations against a manifest checked
into the repository rather than calling the GitHub API itself. Run this
script (requires `gh` authenticated against this repository) whenever a
new issue or PR is opened and referenced by number in a doc, or whenever
the reference guard reports a false positive caused by a stale manifest:

    python3 scripts/refresh_known_references.py

The manifest is one issue/PR number per line (plus a couple of leading
'#'-comment lines), not JSON: tests/fixtures/known_references.txt carries
`merge=union` in .gitattributes so two branches that each append a
different number merge without a conflict (see #190). A `union` merge
driver takes both sides' added lines instead of leaving conflict markers,
but it operates per line and does not re-sort -- that only matters for
this file's readability, since the guard reads it as a set.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = "jonhill90/agent-dotfiles"
MANIFEST_PATH = Path(__file__).parents[1] / "tests" / "fixtures" / "known_references.txt"
MANIFEST_HEADER = (
    "# generated by scripts/refresh_known_references.py -- do not hand-edit\n"
    f"# repo: {REPO}\n"
)


def fetch_numbers(kind: str) -> list[int]:
    result = subprocess.run(
        ["gh", kind, "list", "--repo", REPO, "--state", "all", "--json", "number", "--limit", "1000"],
        capture_output=True,
        text=True,
        check=True,
    )
    return [item["number"] for item in json.loads(result.stdout)]


def main() -> int:
    numbers = sorted(set(fetch_numbers("issue")) | set(fetch_numbers("pr")))
    MANIFEST_PATH.write_text(
        MANIFEST_HEADER + "\n".join(str(n) for n in numbers) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {len(numbers)} known reference numbers to {MANIFEST_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
