#!/usr/bin/env python3
"""agent-dotfiles sync wrapper — everything APM does not own (SPEC §7).

Commands:
  apply   preflight -> apm install -g -> teardown -> Pi projection ->
          settings merges -> state file
  status  report managed surfaces vs recorded state
  doctor  environment checks (CLIs, env vars, root-file ownership)
  remove  reverse everything recorded in state

Python 3 stdlib only. Idempotent throughout.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

APM_MARKER = "Generated by APM CLI"
SYNC_MARKER = "<!-- Generated by agent-dotfiles sync; edits will be overwritten -->"
ABSENT = "__ABSENT__"

# Harnesses whose root files the dotfiles intentionally manage.
MANAGED_ROOT_FILES = (
    Path(".claude/CLAUDE.md"),
    Path(".codex/AGENTS.md"),
    Path(".copilot/AGENTS.md"),
)

# Root files APM's global compile writes for harnesses Jon does not use
# (live-trial wart 3). Removed on apply iff APM-marker-owned.
UNUSED_ROOT_FILES = (
    Path(".cursor/AGENTS.md"),
    Path(".kiro/AGENTS.md"),
    Path(".hermes/AGENTS.md"),
    Path(".config/opencode/AGENTS.md"),
    Path(".codeium/windsurf/AGENTS.md"),
    Path(".gemini/GEMINI.md"),
    Path(".gemini/antigravity-cli/AGENTS.md"),
)

CORPORATE_MOUNT_HINTS = ("OneDrive-SharedLibraries",)


def is_corporate_mount(path: str) -> bool:
    if any(hint in path for hint in CORPORATE_MOUNT_HINTS):
        return True
    for part in Path(path).parts:
        if part.startswith("OneDrive-") and part != "OneDrive-Personal":
            return True
    return False


def strip_frontmatter(text: str) -> str:
    lines = text.splitlines()
    if lines and lines[0] == "---":
        try:
            closing = lines.index("---", 1)
            return "\n".join(lines[closing + 1 :]).lstrip("\n")
        except ValueError:
            pass
    return text


def deep_merge(base: dict, patch: dict) -> dict:
    out = dict(base)
    for key, value in patch.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = deep_merge(out[key], value)
        else:
            out[key] = value
    return out


class Sync:
    def __init__(self, repo_root: Path, home: Path | None = None) -> None:
        self.repo = Path(repo_root)
        self.home = Path(home) if home else Path.home()
        self.runner = subprocess.run
        self.state_file = self.home / ".agent-dotfiles" / "state.json"
        self.state = self._load_state()

    # -- state ------------------------------------------------------------

    def _load_state(self) -> dict:
        if self.state_file.is_file():
            return json.loads(self.state_file.read_text(encoding="utf-8"))
        return {"version": 1, "settings": {}, "pi_agents_md": None, "removed": []}

    def save_state(self) -> None:
        self.state_file.parent.mkdir(parents=True, exist_ok=True)
        self.state_file.write_text(
            json.dumps(self.state, indent=2) + "\n", encoding="utf-8"
        )

    # -- pi projection ----------------------------------------------------

    def pi_available(self) -> bool:
        return shutil.which("pi") is not None

    def project_pi(self) -> Path | None:
        pi_dir = self.home / ".pi" / "agent"
        if not pi_dir.is_dir():
            # pi installed but never launched (fresh machine): initialize
            if self.pi_available():
                pi_dir.mkdir(parents=True, exist_ok=True)
            else:
                return None
        target = pi_dir / "AGENTS.md"
        if target.exists() and SYNC_MARKER not in target.read_text(encoding="utf-8"):
            print(f"[skip] hand-authored, not overwriting: {target}")
            return None

        core = strip_frontmatter(
            (self.repo / "instructions" / "global.instructions.md").read_text(
                encoding="utf-8"
            )
        )
        overlay = (self.repo / "instructions" / "overlays" / "pi.md").read_text(
            encoding="utf-8"
        )
        target.write_text(
            f"{SYNC_MARKER}\n\n{core.strip()}\n\n{overlay.strip()}\n",
            encoding="utf-8",
        )
        self.state["pi_agents_md"] = str(target)
        return target

    def ensure_neutral_skills(self) -> None:
        """APM's neutral-path (~/.agents/skills) targeting is unreliable on
        fresh machines; mirror claude-scope skills into it when empty so
        Pi/Codex/Copilot always see the canonical set."""
        neutral = self.home / ".agents" / "skills"
        claude_skills = self.home / ".claude" / "skills"
        if not claude_skills.is_dir():
            return
        neutral.mkdir(parents=True, exist_ok=True)
        for skill in sorted(claude_skills.iterdir()):
            target = neutral / skill.name
            if skill.is_dir() and not target.exists():
                target.symlink_to(skill)

    # -- teardown ---------------------------------------------------------

    def teardown_unused_root_files(self) -> list[Path]:
        removed: list[Path] = []
        for relative in UNUSED_ROOT_FILES:
            path = self.home / relative
            if path.is_file() and APM_MARKER in path.read_text(encoding="utf-8"):
                path.unlink()
                removed.append(path)
        self.state["removed"] = sorted(
            set(self.state.get("removed", [])) | {str(p) for p in removed}
        )
        return removed

    # -- settings ---------------------------------------------------------

    def merge_settings(self, fragment_name: str, live_path: Path) -> None:
        fragment_file = self.repo / "settings" / fragment_name / "settings.json"
        if not fragment_file.is_file():
            return
        fragment = json.loads(fragment_file.read_text(encoding="utf-8"))
        if not fragment:
            return

        live = {}
        if live_path.is_file():
            live = json.loads(live_path.read_text(encoding="utf-8"))

        previous = self.state["settings"].setdefault(str(live_path), {})
        for key in fragment:
            if key not in previous:
                previous[key] = live.get(key, ABSENT)

        live_path.parent.mkdir(parents=True, exist_ok=True)
        live_path.write_text(
            json.dumps(deep_merge(live, fragment), indent=2) + "\n",
            encoding="utf-8",
        )

    # -- commands ---------------------------------------------------------

    def apply(self, no_apm: bool = False) -> int:
        if not (self.repo / "apm.yml").is_file():
            print(f"ERROR: {self.repo} is not the agent-dotfiles repo")
            return 2
        # ensure the neutral user-scope skills path exists so APM
        # populates it even when no other harness is detected yet
        (self.home / ".agents" / "skills").mkdir(parents=True, exist_ok=True)
        if not no_apm:
            result = self.runner(
                ["apm", "install", "-g", str(self.repo)], check=False
            )
            if result.returncode != 0:
                print("ERROR: apm install failed; aborting apply")
                return result.returncode
            # install does NOT reliably compile root files on fresh
            # machines (E16 failure 2026-07-13) — compile explicitly,
            # BEFORE teardown so stale unused-harness roots are removed.
            self.runner(["apm", "compile", "-g"], check=False)
        self.ensure_neutral_skills()
        removed = self.teardown_unused_root_files()
        pi = self.project_pi()
        self.merge_settings("claude", self.home / ".claude" / "settings.json")
        self.merge_settings("pi", self.home / ".pi" / "agent" / "settings.json")
        self.state["repo"] = str(self.repo)
        self.save_state()
        print(f"[ok] apply complete (teardown: {len(removed)}, pi: {bool(pi)})")
        return 0

    def status(self) -> int:
        issues = 0
        for relative in MANAGED_ROOT_FILES:
            path = self.home / relative
            if not path.parent.is_dir():
                print(f"[skip] {path} (harness not installed)")
                continue
            if not path.is_file():
                print(f"[missing] {path}")
                issues += 1
            elif APM_MARKER not in path.read_text(encoding="utf-8"):
                print(f"[unmanaged] {path} (no APM marker)")
                issues += 1
            else:
                print(f"[ok] {path}")
        for relative in UNUSED_ROOT_FILES:
            path = self.home / relative
            if path.is_file() and APM_MARKER in path.read_text(encoding="utf-8"):
                print(f"[stale] {path} (marker-owned, unused harness)")
                issues += 1
        pi = self.state.get("pi_agents_md")
        if pi:
            print(f"[ok] {pi}" if Path(pi).is_file() else f"[missing] {pi}")
        print(f"{issues} issue(s)")
        return 1 if issues else 0

    def doctor_checks(self, env: dict) -> list[tuple[str, tuple[bool | None, str]]]:
        checks: list[tuple[str, tuple[bool | None, str]]] = []
        checks.append(
            ("apm-cli", (shutil.which("apm") is not None, "apm on PATH"))
        )
        checks.append(
            (
                "cowork-pin",
                (
                    bool(env.get("APM_COPILOT_COWORK_SKILLS_DIR")) or None,
                    "APM_COPILOT_COWORK_SKILLS_DIR (needed with multiple OneDrive mounts)",
                ),
            )
        )
        vault = env.get("AGENT_MEMORY_VAULT")
        if not vault:
            checks.append(
                ("memory-vault-personal", (None, "AGENT_MEMORY_VAULT not set (M4)"))
            )
        elif is_corporate_mount(vault):
            checks.append(
                (
                    "memory-vault-personal",
                    (False, f"memory vault on a corporate mount: {vault}"),
                )
            )
        elif not Path(vault).is_dir():
            checks.append(
                (
                    "memory-vault-personal",
                    (False, f"memory vault path does not exist: {vault}"),
                )
            )
        else:
            checks.append(("memory-vault-personal", (True, vault)))
        claude_md = self.home / ".claude" / "CLAUDE.md"
        if not (self.home / ".claude").is_dir():
            checks.append(
                ("claude-root-file", (None, "Claude Code not installed"))
            )
        else:
            checks.append(
                (
                    "claude-root-file",
                    (
                        claude_md.is_file()
                        and APM_MARKER in claude_md.read_text(encoding="utf-8"),
                        str(claude_md),
                    ),
                )
            )
        return checks

    def doctor(self, env: dict) -> int:
        failed = 0
        for name, (ok, detail) in self.doctor_checks(env=env):
            if ok is True:
                print(f"[pass] {name}: {detail}")
            elif ok is None:
                print(f"[warn] {name}: {detail}")
            else:
                print(f"[FAIL] {name}: {detail}")
                failed += 1
        return 1 if failed else 0

    def remove(self, no_apm: bool = False) -> int:
        pi = self.state.get("pi_agents_md")
        if pi and Path(pi).is_file():
            text = Path(pi).read_text(encoding="utf-8")
            if SYNC_MARKER in text:
                Path(pi).unlink()
        self.state["pi_agents_md"] = None

        for live_path_str, previous in self.state.get("settings", {}).items():
            live_path = Path(live_path_str)
            if not live_path.is_file():
                continue
            live = json.loads(live_path.read_text(encoding="utf-8"))
            for key, value in previous.items():
                if value == ABSENT:
                    live.pop(key, None)
                else:
                    live[key] = value
            live_path.write_text(
                json.dumps(live, indent=2) + "\n", encoding="utf-8"
            )
        self.state["settings"] = {}

        if not no_apm and self.state.get("repo"):
            subprocess.run(
                ["apm", "uninstall", "-g", self.state["repo"]], check=False
            )
        self.save_state()
        print("[ok] remove complete")
        return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["apply", "status", "doctor", "remove"])
    parser.add_argument(
        "--no-apm", action="store_true", help="skip apm install/uninstall"
    )
    args = parser.parse_args()

    import os

    syncer = Sync(repo_root=Path(__file__).resolve().parents[1])
    if args.command == "apply":
        return syncer.apply(no_apm=args.no_apm)
    if args.command == "status":
        return syncer.status()
    if args.command == "doctor":
        return syncer.doctor(env=dict(os.environ))
    return syncer.remove(no_apm=args.no_apm)


if __name__ == "__main__":
    sys.exit(main())
