"""Global APM manifest parsing: stale local-package registrations (#14),
split out of the former scripts/sync.py (2141 lines, agent-dotfiles#335).

apm install -g is additive: every `apm install -g <path>` a machine has
ever run adds a `path:`-registered entry to ~/.apm/apm.yml and leaves its
content cached in ~/.apm/apm_modules/_local/<name>. Neither is pruned
when the source directory is deleted, moved, or its content changes
shape (a skill renamed or removed upstream). The #11 deployment surfaced
exactly this: two registrations pointed at deleted temp directories, and
a third (jonhill90/skills' local checkout) had drifted -- three of its
twelve requested skill names (`az-devops`, `gh-cli`, `using-tmux`) no
longer exist there, having been deleted or renamed since that
registration was made. apm's own compile step accumulated stale cached
content from all of them into ~/.copilot/copilot-instructions.md.

Pure move -- no behaviour change from the original module.
"""

from __future__ import annotations

import re
from pathlib import Path

from sync_skills import apm_dependency_block


def parse_global_local_packages(text: str) -> list[dict[str, object]]:
    """Every `path:`-style local entry in ~/.apm/apm.yml's dependencies.apm
    list, as {"path": str, "skills": list[str]}.

    A small line-based reader, not a general YAML parser (this module is
    stdlib-only by design) -- but ~/.apm/apm.yml is machine-generated by
    apm itself, and its own emitter produces three shapes this must all
    handle: `- path: <value>` inline, `- path:` with the value wrapped
    onto the next line (long paths), and a bare `- <value>` string item
    with no `path:` key at all. `skills:` is a nested YAML block list, not
    an inline array, unlike the project-level apm.yml dependency shape
    validate_repository.py's parse_skill_source_dependencies() parses.
    """
    block = apm_dependency_block(text)
    lines = block.splitlines()
    entries: list[dict[str, object]] = []
    i = 0
    while i < len(lines):
        match = re.match(r"^(\s*)- (.*)$", lines[i])
        if not match:
            i += 1
            continue
        indent = len(match.group(1))
        rest = match.group(2)
        entry: dict[str, object] = {}
        key_match = re.match(r"^(\w+):\s*(.*)$", rest)
        if key_match:
            key, value = key_match.group(1), key_match.group(2).strip()
            if key == "path" and not value and i + 1 < len(lines):
                i += 1
                value = lines[i].strip()
            entry[key] = value
        elif rest.strip():
            entry["path"] = rest.strip()
        i += 1
        while i < len(lines):
            candidate = lines[i]
            if not candidate.strip():
                i += 1
                continue
            candidate_indent = len(candidate) - len(candidate.lstrip(" "))
            if candidate_indent <= indent:
                break
            nested = re.match(r"^\s*(\w+):\s*(.*)$", candidate)
            if nested and nested.group(1) == "skills" and not nested.group(2).strip():
                skills: list[str] = []
                base_indent = candidate_indent
                i += 1
                while i < len(lines):
                    item = lines[i]
                    if not item.strip():
                        i += 1
                        continue
                    item_indent = len(item) - len(item.lstrip(" "))
                    if item_indent <= base_indent:
                        break
                    item_match = re.match(r"^\s*- (.+)$", item)
                    if item_match:
                        skills.append(item_match.group(1).strip())
                    i += 1
                entry["skills"] = skills
                continue
            if nested:
                entry[nested.group(1)] = nested.group(2).strip()
            i += 1
        entries.append(entry)
    return entries


def stale_global_registration(entry: dict[str, object]) -> str | None:
    """None if `entry` (from parse_global_local_packages) is fine; else a
    human-readable reason it is stale.

    A registration with its own apm.yml is *never* flagged, regardless of
    what its skills: selection asks for -- a real project's manifest is
    authoritative about itself, and #14 explicitly requires not rejecting
    a legitimate independent global package just because its local
    skills/ directory happens to differ from what was last requested.

    A bare skill-bundle registration (no apm.yml of its own) is stale if
    its source directory is gone, if it has no package markers at all
    (no apm.yml, no root SKILL.md, no skills/<name>/SKILL.md bundle), or
    if any name it explicitly requested is no longer present in its
    skills/ bundle -- the shape of the real jonhill90/skills local
    checkout after #126 renamed and deleted skills out from under an
    already-registered, un-refreshed dependency.
    """
    path = entry.get("path")
    if not path or not isinstance(path, str):
        return "no path recorded"
    root = Path(path)
    if not root.is_dir():
        return f"source directory no longer exists: {path}"
    if (root / "apm.yml").is_file():
        return None
    has_root_skill = (root / "SKILL.md").is_file()
    skills_dir = root / "skills"
    bundle_names = (
        {d.name for d in skills_dir.iterdir() if d.is_dir() and (d / "SKILL.md").is_file()}
        if skills_dir.is_dir()
        else set()
    )
    if not has_root_skill and not bundle_names:
        return (
            "source no longer contains an APM package (no apm.yml, "
            "SKILL.md, or skills/<name>/SKILL.md)"
        )
    requested = entry.get("skills") or []
    if not isinstance(requested, list):
        # parse_global_local_packages only parses the block-list shape
        # apm's own emitter writes; a flow-style `skills: [a, b]` (or any
        # other hand-edited or foreign-tool-written shape) is stored as a
        # raw, unparsed string instead. Fail closed rather than trust it
        # or crash -- an `assert` here was the prior behaviour, which both
        # raises uncontrolled and is compiled out entirely under -O
        # (#15 review).
        return (
            f"skills: value could not be parsed as a list (got "
            f"{type(requested).__name__}); treating as stale to fail closed"
        )
    missing = sorted(name for name in requested if name not in bundle_names)
    if bundle_names and missing:
        return f"requested skill(s) no longer in source: {', '.join(missing)}"
    return None


def basename_collisions(entries: list[dict[str, object]]) -> dict[str, list[str]]:
    """Group every local registration's path by `Path(path).name`, and
    return only the groups with more than one member (#15 review).

    apm's local cache (`~/.apm/apm_modules/_local/<name>`) and its
    compiled `apm:source` marker names are both keyed by basename only --
    not the full path. `stale_global_registration()` classifies each
    registration on its own; it cannot see that two *distinct* full paths
    (or a distinct path and a legitimate one) share that one cache slot,
    which is real and not hypothetical: the actual global manifest that
    motivated #14 had two different stale temp-directory registrations
    that both ended in `/repo`. `apm uninstall -g <exact-path>` for one
    does not by itself prove the other's identity is untouched, so this
    check exists independently of staleness -- a collision between two
    otherwise-legitimate registrations is exactly as unsafe.
    """
    by_basename: dict[str, list[str]] = {}
    for entry in entries:
        path = entry.get("path")
        if not path or not isinstance(path, str):
            continue
        by_basename.setdefault(Path(path).name, []).append(path)
    return {name: paths for name, paths in by_basename.items() if len(paths) > 1}
