"""Markers and path tables shared across the sync.py split (agent-dotfiles#335).

Split out of the former scripts/sync.py (2141 lines) so each responsibility
module imports only the constants it needs. Pure move -- no behaviour
change from the original module.
"""

from __future__ import annotations

import re
from pathlib import Path

APM_MARKER = "Generated by APM CLI"
SYNC_MARKER = "<!-- Generated by agent-dotfiles sync; edits will be overwritten -->"

# Harnesses that natively read the shared ~/.agents/skills path (SPEC §5),
# so per-harness scoping there is bounded to their union (SPEC §4.1).
NEUTRAL_HARNESSES = ("pi", "codex", "copilot")
ABSENT = "__ABSENT__"
CODEX_MCP_BEGIN = "# >>> agent-dotfiles mcp (managed; do not edit) >>>"
CODEX_MCP_END = "# <<< agent-dotfiles mcp <<<"
CODEX_SKILLS_BEGIN = "# >>> agent-dotfiles skills (managed; do not edit) >>>"
CODEX_SKILLS_END = "# <<< agent-dotfiles skills <<<"
OVERLAY_BEGIN = "<!-- >>> agent-dotfiles overlay (managed; do not edit) >>> -->"
OVERLAY_END = "<!-- <<< agent-dotfiles overlay <<< -->"

# Root context file per harness, and the overlay that may extend it. APM
# compiles the canonical instructions into these; the overlay is appended
# afterwards, marker-delimited, so an instruction needed by one harness is
# not billed to the others (SPEC §4.1, extended to instructions 2026-07-27).
# Pi is absent: its root file is written whole by project_pi(), which already
# composes core + overlay.
# Every file the harness actually reads, not every file APM writes. Copilot
# reads copilot-instructions.md; writing the overlay only to its AGENTS.md
# left the rule out of context entirely, which four eval runs then measured
# as "the sentence does not bind" (2026-07-27).
HARNESS_ROOT_FILES = {
    "claude": (Path(".claude/CLAUDE.md"),),
    "codex": (Path(".codex/AGENTS.md"),),
    "copilot": (Path(".copilot/AGENTS.md"), Path(".copilot/copilot-instructions.md")),
}
OVERLAY_FILES = {
    "claude": "claude-code.md",
    "codex": "codex.md",
    "copilot": "copilot.md",
}

# Harnesses whose root files the dotfiles intentionally manage.
MANAGED_ROOT_FILES = (
    Path(".claude/CLAUDE.md"),
    Path(".codex/AGENTS.md"),
    Path(".copilot/AGENTS.md"),
)

# Every managed *compiled* root, for the apm:source duplicate/foreign scan
# (#14) -- a superset of MANAGED_ROOT_FILES: Copilot's legacy
# copilot-instructions.md surface and Pi's root both get scanned too, even
# though Pi's is written directly by project_pi() (SYNC_MARKER, never
# apm:source) and will simply never produce a finding.
COMPILED_ROOT_FILES = MANAGED_ROOT_FILES + (
    Path(".copilot/copilot-instructions.md"),
    Path(".pi/agent/AGENTS.md"),
)

SOURCE_BLOCK_RE = re.compile(r"<!-- apm:source:(\S+?) -->")

# Root files APM's global compile writes for harnesses Jon does not use
# (live-trial wart 3). Removed on apply iff APM-marker-owned.
UNUSED_ROOT_FILES = (
    Path(".cursor/AGENTS.md"),
    Path(".kiro/AGENTS.md"),
    Path(".hermes/AGENTS.md"),
    Path(".config/opencode/AGENTS.md"),
    Path(".codeium/windsurf/AGENTS.md"),
    Path(".gemini/GEMINI.md"),
    Path(".gemini/antigravity-cli/AGENTS.md"),
)
