"""Managed root-file teardown, overlay projection, and drift detection
(agent-dotfiles#335).

Split out of the former scripts/sync.py (2141 lines). Pure move -- no
behaviour change from the original module.
"""

from __future__ import annotations

import re
from pathlib import Path

from sync_constants import (
    APM_MARKER,
    HARNESS_ROOT_FILES,
    MANAGED_ROOT_FILES,
    OVERLAY_BEGIN,
    OVERLAY_END,
    SOURCE_BLOCK_RE,
    SYNC_MARKER,
    UNUSED_ROOT_FILES,
)
from sync_util import overlay_body, strip_frontmatter


class RootFilesMixin:
    # -- teardown -----------------------------------------------------------

    def teardown_unused_root_files(self) -> list[Path]:
        removed: list[Path] = []
        for relative in UNUSED_ROOT_FILES:
            path = self.home / relative
            if path.is_file() and APM_MARKER in path.read_text(encoding="utf-8"):
                path.unlink()
                removed.append(path)
        self.state["removed"] = sorted(
            set(self.state.get("removed", [])) | {str(p) for p in removed}
        )
        return removed

    def detach_managed_root_files(self) -> dict[Path, str]:
        """Remove only APM-owned roots so compile cannot reuse stale output."""
        backups: dict[Path, str] = {}
        for relative in MANAGED_ROOT_FILES:
            path = self.home / relative
            if not path.is_file():
                continue
            text = path.read_text(encoding="utf-8")
            if APM_MARKER in text:
                backups[path] = text
                path.unlink()
        return backups

    @staticmethod
    def restore_root_files(backups: dict[Path, str]) -> None:
        for path, text in backups.items():
            if not path.exists():
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")

    def compiled_root_source_findings(self, path: Path) -> list[str]:
        """Duplicate or foreign `apm:source` blocks in a compiled root
        file (#14).

        `<!-- apm:source:NAME --> ... <!-- /apm:source -->` is the marker
        convention apm's *legacy* Copilot surface uses for
        `copilot-instructions.md` -- a different convention entirely from
        the single `<!-- Generated by APM CLI -->` line the other root
        files carry (checked via APM_MARKER elsewhere). A file using
        neither, or exactly one block naming the current local package,
        is fine. Anything else is exactly the #11 incident: apm's cache
        accumulating content from every local package ever registered.
        """
        if not path.is_file():
            return []
        text = path.read_text(encoding="utf-8")
        names = SOURCE_BLOCK_RE.findall(text)
        if not names:
            return []
        expected = f"_local/{self.repo.name}"
        findings: list[str] = []
        if len(names) != 1:
            findings.append(f"{len(names)} apm:source blocks (expected 1)")
        foreign = sorted({name for name in names if name != expected})
        if foreign:
            findings.append(f"foreign source block(s): {', '.join(foreign)}")
        return findings

    # -- instruction overlays -------------------------------------------------

    @staticmethod
    def _strip_overlay_block(text: str) -> str:
        pattern = re.compile(
            r"\n*" + re.escape(OVERLAY_BEGIN) + r".*?" + re.escape(OVERLAY_END) + r"\n?",
            re.S,
        )
        return pattern.sub("", text)

    @staticmethod
    def _deployed_overlay_body(text: str) -> str:
        """The overlay body a deployed root file currently carries, or ""
        if it carries none -- the inverse of the block `apply_overlays`
        writes, so it can be compared directly against `overlay_body`."""
        match = re.search(
            re.escape(OVERLAY_BEGIN) + r"\n\n(.*?)\n\n" + re.escape(OVERLAY_END),
            text,
            re.S,
        )
        return match.group(1) if match else ""

    def instructions_drift(self) -> list[str]:
        """Deployed instructions/overlays whose content disagrees with the
        repository (#36).

        `sync.py` had real drift detection for skills only
        (`neutral_drift`/`neutral_identity`) -- nothing compared deployed
        *instructions* against the repo, so `status` could report `0
        issue(s)` while `instructions/overlays/copilot.md` had moved on
        `main` and the deployed copy had not. Mirrors #35/#37's fix
        rather than inventing a second mechanism: compare deployed content
        against a source that exists at check time, offline, with no
        change to `apply()`.

        Scope is deliberately the overlay, not the compiled core. The core
        portion of each `HARNESS_ROOT_FILES` entry is written by `apm
        compile`, which this check cannot reproduce offline without
        running `apm` -- the same reason #37 rejected an apply-time hash
        manifest as a source of truth here. The overlay is different: it
        is appended by `apply_overlays` itself, deterministically, from
        `overlay_body(repo, harness)` alone, so it can be recomputed and
        compared without touching `apply()` or the network.

        Copilot reads `copilot-instructions.md`, not `AGENTS.md` -- a
        wrapper bug of exactly this kind was already caught once by an
        eval (see `HARNESS_ROOT_FILES`). Iterating every path in
        `HARNESS_ROOT_FILES`, not just one per harness, is what makes that
        distinction load-bearing here rather than assumed away.

        A root file that does not exist yet is skipped, not reported --
        that is "never applied", which is `neutral_drift`'s and
        `apply()`'s job, not this one's. Pi is handled separately: its
        root file is written directly by `project_pi()` (core + overlay,
        no APM compile step), so the *whole* file is reproducible offline
        and compared whole -- except when it is hand-authored (no
        `SYNC_MARKER`), which `project_pi()` itself already refuses to
        touch.
        """
        drifted: list[str] = []
        for harness, rels in HARNESS_ROOT_FILES.items():
            expected = overlay_body(self.repo, harness)
            for rel in rels:
                path = self.home / rel
                if not path.is_file():
                    continue
                deployed = self._deployed_overlay_body(
                    path.read_text(encoding="utf-8")
                )
                if deployed != expected:
                    drifted.append(str(path))
        pi_path = self.home / ".pi" / "agent" / "AGENTS.md"
        if pi_path.is_file():
            text = pi_path.read_text(encoding="utf-8")
            if SYNC_MARKER in text:
                core = strip_frontmatter(
                    (self.repo / "instructions" / "global.instructions.md").read_text(
                        encoding="utf-8"
                    )
                )
                overlay = (self.repo / "instructions" / "overlays" / "pi.md").read_text(
                    encoding="utf-8"
                )
                expected_pi = f"{SYNC_MARKER}\n\n{core.strip()}\n\n{overlay.strip()}\n"
                if text != expected_pi:
                    drifted.append(str(pi_path))
        return sorted(drifted)

    def apply_overlays(self) -> list[Path]:
        """Append each harness's overlay to its APM-compiled root file.

        Runs after `apm compile`, which owns the canonical portion. The block
        is marker-delimited so re-applying replaces rather than duplicates,
        emptying the overlay removes it, and teardown can strip it.
        """
        written: list[Path] = []
        for harness, rels in HARNESS_ROOT_FILES.items():
          for rel in rels:
            root = self.home / rel
            if not root.is_file():
                continue
            text = root.read_text(encoding="utf-8")
            base = self._strip_overlay_block(text)
            body = overlay_body(self.repo, harness)
            if body:
                new = (base.rstrip("\n") + "\n\n" + OVERLAY_BEGIN + "\n\n"
                       + body + "\n\n" + OVERLAY_END + "\n")
                written.append(root)
            else:
                new = base
            if new != text:
                root.write_text(new, encoding="utf-8")
        self.state["overlays"] = [str(p) for p in written]
        return written
