#!/usr/bin/env python3
"""agent-dotfiles sync wrapper — everything APM does not own (SPEC §7).

Commands:
  apply   preflight -> apm install -g -> teardown -> Pi projection ->
          settings merges -> mcp merge -> state file
  status  report managed surfaces vs recorded state
  doctor  environment checks (CLIs, env vars, root-file ownership)
  remove  reverse everything recorded in state

Python 3 stdlib only. Idempotent throughout.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

APM_MARKER = "Generated by APM CLI"
SYNC_MARKER = "<!-- Generated by agent-dotfiles sync; edits will be overwritten -->"
# Harnesses that natively read the shared ~/.agents/skills path (SPEC §5),
# so per-harness scoping there is bounded to their union (SPEC §4.1).
NEUTRAL_HARNESSES = ("pi", "codex", "copilot")
ABSENT = "__ABSENT__"
CODEX_MCP_BEGIN = "# >>> agent-dotfiles mcp (managed; do not edit) >>>"
CODEX_MCP_END = "# <<< agent-dotfiles mcp <<<"
CODEX_SKILLS_BEGIN = "# >>> agent-dotfiles skills (managed; do not edit) >>>"
CODEX_SKILLS_END = "# <<< agent-dotfiles skills <<<"
OVERLAY_BEGIN = "<!-- >>> agent-dotfiles overlay (managed; do not edit) >>> -->"
OVERLAY_END = "<!-- <<< agent-dotfiles overlay <<< -->"

# Root context file per harness, and the overlay that may extend it. APM
# compiles the canonical instructions into these; the overlay is appended
# afterwards, marker-delimited, so an instruction needed by one harness is
# not billed to the others (SPEC §4.1, extended to instructions 2026-07-27).
# Pi is absent: its root file is written whole by project_pi(), which already
# composes core + overlay.
# Every file the harness actually reads, not every file APM writes. Copilot
# reads copilot-instructions.md; writing the overlay only to its AGENTS.md
# left the rule out of context entirely, which four eval runs then measured
# as "the sentence does not bind" (2026-07-27).
HARNESS_ROOT_FILES = {
    "claude": (Path(".claude/CLAUDE.md"),),
    "codex": (Path(".codex/AGENTS.md"),),
    "copilot": (Path(".copilot/AGENTS.md"), Path(".copilot/copilot-instructions.md")),
}
OVERLAY_FILES = {
    "claude": "claude-code.md",
    "codex": "codex.md",
    "copilot": "copilot.md",
}


def _description_of(skill_md: Path) -> str:
    """A skill's `description`, whitespace-normalised, or "" if unreadable."""
    try:
        text = skill_md.read_text(encoding="utf-8")
    except OSError:
        return ""
    match = re.search(r"^description:\s*(.*?)(?=^\w+:|^---)", text, re.M | re.S)
    return " ".join(match.group(1).split()) if match else ""


def overlay_body(repo: Path, harness: str) -> str:
    """An overlay's content, or "" when it is a placeholder.

    A file that only documents why it is empty must not produce a block —
    `claude-code.md` is deliberately empty and says so at length.
    """
    name = OVERLAY_FILES.get(harness)
    if not name:
        return ""
    path = repo / "instructions" / "overlays" / name
    if not path.is_file():
        return ""
    raw = re.sub(r"<!--.*?-->", "", path.read_text(encoding="utf-8"), flags=re.S)
    lines = [
        line for line in raw.splitlines()
        if line.strip() and not line.startswith("#")
    ]
    body = "\n".join(lines).strip()
    if not body or "intentionally empty" in body.lower():
        return ""
    return body

# Harnesses whose root files the dotfiles intentionally manage.
MANAGED_ROOT_FILES = (
    Path(".claude/CLAUDE.md"),
    Path(".codex/AGENTS.md"),
    Path(".copilot/AGENTS.md"),
)

# Root files APM's global compile writes for harnesses Jon does not use
# (live-trial wart 3). Removed on apply iff APM-marker-owned.
UNUSED_ROOT_FILES = (
    Path(".cursor/AGENTS.md"),
    Path(".kiro/AGENTS.md"),
    Path(".hermes/AGENTS.md"),
    Path(".config/opencode/AGENTS.md"),
    Path(".codeium/windsurf/AGENTS.md"),
    Path(".gemini/GEMINI.md"),
    Path(".gemini/antigravity-cli/AGENTS.md"),
)

CORPORATE_MOUNT_HINTS = ("OneDrive-SharedLibraries",)


def is_corporate_mount(path: str) -> bool:
    if any(hint in path for hint in CORPORATE_MOUNT_HINTS):
        return True
    for part in Path(path).parts:
        if part.startswith("OneDrive-") and part != "OneDrive-Personal":
            return True
    return False


def strip_frontmatter(text: str) -> str:
    lines = text.splitlines()
    if lines and lines[0] == "---":
        try:
            closing = lines.index("---", 1)
            return "\n".join(lines[closing + 1 :]).lstrip("\n")
        except ValueError:
            pass
    return text


def deep_merge(base: dict, patch: dict) -> dict:
    out = dict(base)
    for key, value in patch.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = deep_merge(out[key], value)
        else:
            out[key] = value
    return out


def load_skill_roster(repo: Path) -> tuple[list[str], dict[str, list[str]]]:
    """Parse `settings/default-skills.txt` into (shared, per-harness sections).

    Lines before any `[harness]` header are shared by every harness, so a
    flat file keeps its original meaning (SPEC §4.1).
    """
    roster = repo / "settings" / "default-skills.txt"
    shared: list[str] = []
    sections: dict[str, list[str]] = {}
    current: list[str] | None = None
    for raw in roster.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            current = sections.setdefault(line[1:-1].strip().lower(), [])
            continue
        (shared if current is None else current).append(line)
    return shared, sections


def load_default_skills(repo: Path, harness: str | None = None) -> list[str]:
    """Resolved roster: shared alone, or shared + that harness's section."""
    shared, sections = load_skill_roster(repo)
    if harness is None:
        return shared
    return shared + sections.get(harness.lower(), [])


def roster_union(repo: Path) -> list[str]:
    """Every skill any harness asks for — what APM installs (SPEC §4.1)."""
    shared, sections = load_skill_roster(repo)
    names = set(shared)
    for values in sections.values():
        names.update(values)
    return sorted(names)


def neutral_union(repo: Path) -> list[str]:
    """What the shared `~/.agents/skills` path may contain: the neutral
    trio's rosters only, so Claude-scoped skills never leak into it."""
    shared, sections = load_skill_roster(repo)
    names = set(shared)
    for harness in NEUTRAL_HARNESSES:
        names.update(sections.get(harness, []))
    return sorted(names)


def claude_skill_overrides(repo: Path) -> dict[str, str]:
    """`skillOverrides` entries that enforce Claude Code's resolved roster.

    APM installs the union into `~/.claude/skills` and keeps ownership of it
    (SPEC §4.1), so a skill scoped away from Claude Code still reaches the
    model's list. V9 resolved the Tier B lever — `skillOverrides` with a value
    of `off` — and this derives it from the roster so the declaration and the
    enforcement cannot drift.
    """
    claude = set(load_default_skills(repo, "claude"))
    return {name: "off" for name in roster_union(repo) if name not in claude}


def copilot_disabled_skills(repo: Path) -> list[str]:
    """`disabledSkills` entries that enforce Copilot's resolved roster.

    Copilot discovers personal skills from `~/.agents/skills` — the directory
    the neutral harnesses share — so a skill scoped to Codex and Pi reaches
    Copilot as well, and Tier A cannot separate them. V10 resolved
    affirmatively on 2026-07-27: `disabledSkills` in `~/.copilot/settings.json`,
    which the wrapper already manages, and a fresh Copilot process stops
    listing the skill. Derived from the roster so the declaration and the
    enforcement cannot drift.
    """
    copilot = set(load_default_skills(repo, "copilot"))
    return [name for name in roster_union(repo) if name not in copilot]


def codex_disabled_skills(repo: Path) -> list[str]:
    """Skill names Codex's resolved roster excludes.

    Codex reads the shared `~/.agents/skills` tree, so Tier A cannot separate
    it from Copilot and Pi. Its Tier B lever is `[[skills.config]]` with
    `enabled = false`. Personal skills are keyed by bare name; plugin skills
    are namespaced (`github:yeet`), which is why the managed block is written
    between markers and the user's own entries are left alone.
    """
    codex = set(load_default_skills(repo, "codex"))
    return [name for name in roster_union(repo) if name not in codex]


def pi_disabled_skills(repo: Path) -> list[str]:
    """Denylist entries enforcing Pi's resolved roster.

    Pi's `skills` key takes paths, and a leading `-` removes one.
    """
    pi = set(load_default_skills(repo, "pi"))
    return [
        f"-skills/{name}/SKILL.md"
        for name in roster_union(repo)
        if name not in pi
    ]


class Sync:
    def __init__(self, repo_root: Path, home: Path | None = None) -> None:
        self.repo = Path(repo_root)
        self.home = Path(home) if home else Path.home()
        self.runner = subprocess.run
        self.state_file = self.home / ".agent-dotfiles" / "state.json"
        self.state = self._load_state()

    # -- state ------------------------------------------------------------

    def _load_state(self) -> dict:
        if self.state_file.is_file():
            return json.loads(self.state_file.read_text(encoding="utf-8"))
        return {
            "version": 1,
            "settings": {},
            "mcp": {},
            "pi_agents_md": None,
            "removed": [],
        }

    def save_state(self) -> None:
        self.state_file.parent.mkdir(parents=True, exist_ok=True)
        self.state_file.write_text(
            json.dumps(self.state, indent=2) + "\n", encoding="utf-8"
        )

    # -- pi projection ----------------------------------------------------

    def pi_available(self) -> bool:
        return shutil.which("pi") is not None

    def project_pi(self) -> Path | None:
        pi_dir = self.home / ".pi" / "agent"
        if not pi_dir.is_dir():
            # pi installed but never launched (fresh machine): initialize
            if self.pi_available():
                pi_dir.mkdir(parents=True, exist_ok=True)
            else:
                return None
        target = pi_dir / "AGENTS.md"
        if target.exists() and SYNC_MARKER not in target.read_text(encoding="utf-8"):
            print(f"[skip] hand-authored, not overwriting: {target}")
            return None

        core = strip_frontmatter(
            (self.repo / "instructions" / "global.instructions.md").read_text(
                encoding="utf-8"
            )
        )
        overlay = (self.repo / "instructions" / "overlays" / "pi.md").read_text(
            encoding="utf-8"
        )
        target.write_text(
            f"{SYNC_MARKER}\n\n{core.strip()}\n\n{overlay.strip()}\n",
            encoding="utf-8",
        )
        self.state["pi_agents_md"] = str(target)
        return target

    def ensure_neutral_skills(self) -> None:
        """APM's neutral-path (~/.agents/skills) targeting is unreliable on
        fresh machines; mirror into it so Pi/Codex/Copilot always see their
        set.

        Tier A scoping (SPEC §4.1): only the neutral trio's resolved roster
        is mirrored, so a Claude-scoped skill never reaches the shared path.
        Links this wrapper created and that have since left the union are
        removed; links it did not create are never touched.
        """
        neutral = self.home / ".agents" / "skills"
        claude_skills = self.home / ".claude" / "skills"
        if not claude_skills.is_dir():
            return
        wanted = set(neutral_union(self.repo))
        managed = set(self.state.get("neutral_skills", []))
        neutral.mkdir(parents=True, exist_ok=True)
        for skill in sorted(claude_skills.iterdir()):
            if not skill.is_dir() or skill.name not in wanted:
                continue
            target = neutral / skill.name
            if not target.exists():
                target.symlink_to(skill)
                managed.add(skill.name)
        for name in sorted(managed - wanted):
            target = neutral / name
            if target.is_symlink():
                target.unlink()
            managed.discard(name)
        self.state["neutral_skills"] = sorted(managed)

    # -- teardown ---------------------------------------------------------

    def teardown_unused_root_files(self) -> list[Path]:
        removed: list[Path] = []
        for relative in UNUSED_ROOT_FILES:
            path = self.home / relative
            if path.is_file() and APM_MARKER in path.read_text(encoding="utf-8"):
                path.unlink()
                removed.append(path)
        self.state["removed"] = sorted(
            set(self.state.get("removed", [])) | {str(p) for p in removed}
        )
        return removed

    def detach_managed_root_files(self) -> dict[Path, str]:
        """Remove only APM-owned roots so compile cannot reuse stale output."""
        backups: dict[Path, str] = {}
        for relative in MANAGED_ROOT_FILES:
            path = self.home / relative
            if not path.is_file():
                continue
            text = path.read_text(encoding="utf-8")
            if APM_MARKER in text:
                backups[path] = text
                path.unlink()
        return backups

    @staticmethod
    def restore_root_files(backups: dict[Path, str]) -> None:
        for path, text in backups.items():
            if not path.exists():
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")

    # -- settings ---------------------------------------------------------

    def merge_settings(self, fragment_name: str, live_path: Path) -> None:
        fragment_file = self.repo / "settings" / fragment_name / "settings.json"
        if not fragment_file.is_file():
            return
        fragment = json.loads(fragment_file.read_text(encoding="utf-8"))
        if fragment_name == "claude":
            # Enforce Claude Code's resolved roster. APM installs the union
            # into ~/.claude/skills, so scoping is only declared until this
            # writes it (SPEC §4.1 Tier B, unlocked by V9).
            overrides = claude_skill_overrides(self.repo)
            if overrides:
                fragment = dict(fragment)
                fragment["skillOverrides"] = deep_merge(
                    fragment.get("skillOverrides", {}), overrides
                )
        if fragment_name == "pi":
            # Pi reads the shared ~/.agents/skills tree too (SPEC §4.1 Tier B,
            # verified under V9). Entries are paths, not names.
            denied = pi_disabled_skills(self.repo)
            if denied:
                fragment = dict(fragment)
                fragment["skills"] = sorted(
                    set(fragment.get("skills", [])) | set(denied)
                )
        if fragment_name == "copilot":
            # Same drift, different directory: Copilot reads the shared
            # ~/.agents/skills tree (SPEC §4.1 Tier B, unlocked by V10).
            disabled = copilot_disabled_skills(self.repo)
            if disabled:
                fragment = dict(fragment)
                fragment["disabledSkills"] = sorted(
                    set(fragment.get("disabledSkills", [])) | set(disabled)
                )
        # Do not bail on an empty fragment when we still own list entries in
        # this file: withdrawing them is exactly the case where the fragment
        # has gone empty because the roster stopped excluding anything.
        if not fragment and not self.state.get("settings_lists", {}).get(
            str(live_path)
        ):
            return

        live = {}
        if live_path.is_file():
            live = json.loads(live_path.read_text(encoding="utf-8"))

        previous = self.state["settings"].setdefault(str(live_path), {})
        for key in fragment:
            if key not in previous:
                previous[key] = live.get(key, ABSENT)

        # List-valued keys need ownership, not replacement and not union.
        # deep_merge replaces lists wholesale, which deletes entries a harness
        # UI or another package wrote. A plain union fixes that and creates
        # the opposite bug: an entry this wrapper wrote earlier can never be
        # withdrawn, which is how a stale `disabledSkills` survived a skill
        # leaving the roster (2026-07-29, found by hand).
        #
        # So: keep what we did not write, drop what we did write and no
        # longer want, add what we want now.
        owned = self.state.setdefault("settings_lists", {}).setdefault(
            str(live_path), {}
        )
        merged = deep_merge(live, fragment)
        # Driven by keys we have ever owned, not only keys in the fragment:
        # when the roster stops excluding anything the key disappears from
        # the fragment entirely, and a withdrawal keyed off the fragment
        # would never fire — which is exactly how the stale entry survived.
        list_keys = {k for k, v in fragment.items() if isinstance(v, list)}
        list_keys |= set(owned)
        for key in list_keys:
            wanted = fragment.get(key, [])
            if not isinstance(wanted, list):
                continue
            foreign = [
                entry for entry in live.get(key, [])
                if entry not in owned.get(key, [])
            ]
            merged[key] = sorted(set(foreign) | set(wanted))
            owned[key] = sorted(set(wanted))

        live_path.parent.mkdir(parents=True, exist_ok=True)
        live_path.write_text(
            json.dumps(merged, indent=2) + "\n",
            encoding="utf-8",
        )

    def restore_settings(self, live_path: Path) -> None:
        """Put one settings file back as it was before the wrapper touched it."""
        previous = self.state.get("settings", {}).get(str(live_path))
        if previous is None or not live_path.is_file():
            return
        live = json.loads(live_path.read_text(encoding="utf-8"))
        for key, value in previous.items():
            if value == ABSENT:
                live.pop(key, None)
            else:
                live[key] = value
        live_path.write_text(json.dumps(live, indent=2) + "\n", encoding="utf-8")
        self.state.get("settings", {}).pop(str(live_path), None)
        self.state.get("settings_lists", {}).pop(str(live_path), None)

    # -- mcp --------------------------------------------------------------

    def mcp_fragment_file(self) -> Path:
        return self.repo / "settings" / "mcp" / "servers.json"

    def declared_mcp_servers(self) -> dict:
        fragment_file = self.mcp_fragment_file()
        if not fragment_file.is_file():
            return {}
        return json.loads(fragment_file.read_text(encoding="utf-8")).get(
            "mcpServers", {}
        )

    def _merge_mcp_json(self, live_path: Path) -> None:
        """Merge the declared servers into a JSON file with a top-level
        mcpServers key, recording previous values for reversal."""
        servers = self.declared_mcp_servers()
        if not servers:
            return
        live = {}
        if live_path.is_file():
            live = json.loads(live_path.read_text(encoding="utf-8"))

        previous = self.state.setdefault("mcp", {}).setdefault(str(live_path), {})
        live_servers = live.get("mcpServers", {})
        for name in servers:
            if name not in previous:
                previous[name] = live_servers.get(name, ABSENT)

        live["mcpServers"] = deep_merge(live_servers, servers)
        live_path.write_text(
            json.dumps(live, indent=2) + "\n", encoding="utf-8"
        )

    def merge_mcp(self) -> None:
        """Project the declared MCP set into Claude Code user scope
        (~/.claude.json). Pi gets none by design (SPEC §3.4)."""
        self._merge_mcp_json(self.home / ".claude.json")

    def merge_copilot_mcp(self) -> None:
        """Copilot CLI reads ~/.copilot/mcp-config.json (same mcpServers
        schema). Only projected when the harness directory exists."""
        if not (self.home / ".copilot").is_dir():
            return
        self._merge_mcp_json(self.home / ".copilot" / "mcp-config.json")

    @staticmethod
    def _strip_codex_block(text: str) -> str:
        pattern = re.compile(
            r"\n*" + re.escape(CODEX_MCP_BEGIN) + r".*?" + re.escape(CODEX_MCP_END) + r"\n?",
            re.S,
        )
        return pattern.sub("", text)

    def merge_codex_mcp(self) -> None:
        """Codex has no user-scope JSON MCP surface; render the declared
        servers as a marker-delimited block in ~/.codex/config.toml.
        Servers the user already defines outside the block are skipped."""
        config = self.home / ".codex" / "config.toml"
        if not config.parent.is_dir():
            return
        servers = self.declared_mcp_servers()
        text = config.read_text(encoding="utf-8") if config.is_file() else ""
        base = self._strip_codex_block(text)

        lines: list[str] = []
        for name, spec in servers.items():
            if f"[mcp_servers.{name}]" in base:
                print(f"[skip] codex mcp: {name} defined outside managed block")
                continue
            lines.append(f"[mcp_servers.{name}]")
            if "url" in spec:
                lines.append(f'url = "{spec["url"]}"')
            auth = spec.get("headers", {}).get("Authorization", "")
            match = re.fullmatch(r"Bearer \$\{(\w+)\}", auth)
            if match:
                lines.append(f'bearer_token_env_var = "{match.group(1)}"')
            lines.append("")

        if lines:
            block = "\n".join([CODEX_MCP_BEGIN, *lines[:-1], CODEX_MCP_END])
            new = (base.rstrip("\n") + "\n\n" + block + "\n").lstrip("\n")
            self.state["codex_mcp"] = str(config)
        else:
            new = base
        if new != text:
            config.write_text(new, encoding="utf-8")

    @staticmethod
    def _strip_overlay_block(text: str) -> str:
        pattern = re.compile(
            r"\n*" + re.escape(OVERLAY_BEGIN) + r".*?" + re.escape(OVERLAY_END) + r"\n?",
            re.S,
        )
        return pattern.sub("", text)

    def apply_overlays(self) -> list[Path]:
        """Append each harness's overlay to its APM-compiled root file.

        Runs after `apm compile`, which owns the canonical portion. The block
        is marker-delimited so re-applying replaces rather than duplicates,
        emptying the overlay removes it, and teardown can strip it.
        """
        written: list[Path] = []
        for harness, rels in HARNESS_ROOT_FILES.items():
          for rel in rels:
            root = self.home / rel
            if not root.is_file():
                continue
            text = root.read_text(encoding="utf-8")
            base = self._strip_overlay_block(text)
            body = overlay_body(self.repo, harness)
            if body:
                new = (base.rstrip("\n") + "\n\n" + OVERLAY_BEGIN + "\n\n"
                       + body + "\n\n" + OVERLAY_END + "\n")
                written.append(root)
            else:
                new = base
            if new != text:
                root.write_text(new, encoding="utf-8")
        self.state["overlays"] = [str(p) for p in written]
        return written

    @staticmethod
    def _strip_codex_skills_block(text: str) -> str:
        pattern = re.compile(
            r"\n*" + re.escape(CODEX_SKILLS_BEGIN) + r".*?"
            + re.escape(CODEX_SKILLS_END) + r"\n?",
            re.S,
        )
        return pattern.sub("", text)

    def merge_codex_skills(self) -> None:
        """Enforce Codex's resolved roster as a managed `[[skills.config]]`
        block in ~/.codex/config.toml (SPEC §4.1 Tier B).

        Marker-delimited because the same table holds the user's own plugin
        disables; stripping and rewriting only the managed span leaves those
        untouched and makes the block reversible on teardown.
        """
        config = self.home / ".codex" / "config.toml"
        if not config.parent.is_dir():
            return
        text = config.read_text(encoding="utf-8") if config.is_file() else ""
        base = self._strip_codex_skills_block(text)

        lines: list[str] = []
        for name in codex_disabled_skills(self.repo):
            lines.extend(["[[skills.config]]", f'name = "{name}"',
                          "enabled = false", ""])
        if lines:
            block = "\n".join([CODEX_SKILLS_BEGIN, *lines[:-1], CODEX_SKILLS_END])
            new = (base.rstrip("\n") + "\n\n" + block + "\n").lstrip("\n")
            self.state["codex_skills"] = str(config)
        else:
            new = base
            self.state["codex_skills"] = None

        if new != text:
            config.write_text(new, encoding="utf-8")

    # -- commands ---------------------------------------------------------

    def apply(self, no_apm: bool = False) -> int:
        if not (self.repo / "apm.yml").is_file():
            print(f"ERROR: {self.repo} is not the agent-dotfiles repo")
            return 2
        # ensure the neutral user-scope skills path exists so APM
        # populates it even when no other harness is detected yet
        (self.home / ".agents" / "skills").mkdir(parents=True, exist_ok=True)
        if not no_apm:
            skill_args = [
                argument
                for skill in roster_union(self.repo)
                for argument in ("--skill", skill)
            ]
            result = self.runner(
                ["apm", "install", "-g", str(self.repo), *skill_args],
                check=False,
            )
            if result.returncode != 0:
                print("ERROR: apm install failed; aborting apply")
                return result.returncode
            # install does NOT reliably compile root files on fresh
            # machines (E16 failure 2026-07-13) — compile explicitly,
            # BEFORE teardown so stale unused-harness roots are removed.
            # Marker-owned managed roots are detached first: APM has also
            # reported "unchanged" for stale output after source edits (V8).
            root_backups = self.detach_managed_root_files()
            compile_result = self.runner(["apm", "compile", "-g"], check=False)
            if compile_result.returncode != 0:
                self.restore_root_files(root_backups)
                print("ERROR: apm compile failed; aborting apply")
                return compile_result.returncode
            # A detected harness should be regenerated. If APM skipped one,
            # preserve its last-known-good marker-owned root instead of
            # turning a refresh into accidental removal.
            self.restore_root_files(root_backups)
        self.apply_overlays()
        self.ensure_neutral_skills()
        removed = self.teardown_unused_root_files()
        pi = self.project_pi()
        self.merge_settings("claude", self.home / ".claude" / "settings.json")
        self.merge_settings("pi", self.home / ".pi" / "agent" / "settings.json")
        if (self.home / ".copilot").is_dir():
            self.merge_settings(
                "copilot", self.home / ".copilot" / "settings.json"
            )
        self.merge_mcp()
        self.merge_codex_skills()
        self.merge_codex_mcp()
        self.merge_copilot_mcp()
        self.state["repo"] = str(self.repo)
        self.save_state()
        print(f"[ok] apply complete (teardown: {len(removed)}, pi: {bool(pi)})")
        return 0

    def status(self) -> int:
        issues = 0
        shared, sections = load_skill_roster(self.repo)
        for harness, names in sorted(self.roster_report().items()):
            scoped = len(names) - len(shared)
            suffix = f" ({len(shared)} shared + {scoped} scoped)" if sections else ""
            print(f"[roster] {harness}: {len(names)} skill(s){suffix}")
        drift = self.neutral_drift()
        if drift:
            print(f"[drift] ~/.agents/skills: unwanted {', '.join(drift)}")
            issues += 1
        substituted = self.neutral_identity()
        if substituted:
            print(
                "[substituted] ~/.agents/skills: not our copy — "
                f"{', '.join(substituted)}"
            )
            issues += 1
        for relative in MANAGED_ROOT_FILES:
            path = self.home / relative
            if not path.parent.is_dir():
                print(f"[skip] {path} (harness not installed)")
                continue
            if not path.is_file():
                print(f"[missing] {path}")
                issues += 1
            elif APM_MARKER not in path.read_text(encoding="utf-8"):
                print(f"[unmanaged] {path} (no APM marker)")
                issues += 1
            else:
                print(f"[ok] {path}")
        for relative in UNUSED_ROOT_FILES:
            path = self.home / relative
            if path.is_file() and APM_MARKER in path.read_text(encoding="utf-8"):
                print(f"[stale] {path} (marker-owned, unused harness)")
                issues += 1
        pi = self.state.get("pi_agents_md")
        if pi:
            print(f"[ok] {pi}" if Path(pi).is_file() else f"[missing] {pi}")
        declared = self.declared_mcp_servers()
        if declared:
            surfaces: list[tuple[str, set[str]]] = []
            claude_json = self.home / ".claude.json"
            if claude_json.is_file():
                names = set(
                    json.loads(claude_json.read_text(encoding="utf-8")).get(
                        "mcpServers", {}
                    )
                )
                surfaces.append(("claude", names))
            codex_toml = self.home / ".codex" / "config.toml"
            if codex_toml.parent.is_dir():
                text = (
                    codex_toml.read_text(encoding="utf-8")
                    if codex_toml.is_file()
                    else ""
                )
                names = {
                    n for n in declared if f"[mcp_servers.{n}]" in text
                }
                surfaces.append(("codex", names))
            copilot_json = self.home / ".copilot" / "mcp-config.json"
            if (self.home / ".copilot").is_dir():
                names = set()
                if copilot_json.is_file():
                    names = set(
                        json.loads(
                            copilot_json.read_text(encoding="utf-8")
                        ).get("mcpServers", {})
                    )
                surfaces.append(("copilot", names))
            for surface, present in surfaces:
                for name in sorted(declared):
                    if name in present:
                        print(f"[ok] mcp:{surface}:{name}")
                    else:
                        print(f"[missing] mcp:{surface}:{name} (declared, not projected)")
                        issues += 1
        print(f"{issues} issue(s)")
        return 1 if issues else 0

    def roster_report(self) -> dict[str, list[str]]:
        """Each harness's resolved roster (SPEC §4.1)."""
        return {
            harness: load_default_skills(self.repo, harness)
            for harness in ("claude", *NEUTRAL_HARNESSES)
        }

    def neutral_drift(self) -> list[str]:
        """Wrapper-managed links on the shared path that no roster wants.

        Auto-removed by the next apply.
        """
        wanted = set(neutral_union(self.repo))
        return sorted(set(self.state.get("neutral_skills", [])) - wanted)

    def neutral_identity(self) -> list[str]:
        """Roster skills on the shared path whose deployed copy is not ours.

        `neutral_untracked` skips any name the roster wants, so a foreign
        skill installed under a managed name is invisible to it — and the
        wrapper owns nothing on that path (`ensure_neutral_skills` only links
        when the target is absent), so nothing else notices either. Three
        harnesses would load a third party's procedure, and its scripts,
        under a trusted name with every check green (#93).

        Compared on the description, not the whole file: APM rewrites
        relative links in the body on install, so byte-comparison reports a
        false mismatch on a legitimately deployed skill.
        """
        mismatched: list[str] = []
        for name in neutral_union(self.repo):
            deployed = self.home / ".agents" / "skills" / name / "SKILL.md"
            source = self.repo / "skills" / name / "SKILL.md"
            if not deployed.is_file() or not source.is_file():
                continue
            if _description_of(deployed) != _description_of(source):
                mismatched.append(name)
        return mismatched

    def neutral_untracked(self) -> list[str]:
        """Out-of-union links on the shared path this wrapper did not create.

        Machines synced before §4.1 carry links from the old wholesale
        mirroring, which are untracked and therefore never auto-removed. A
        harness-scoped skill would stay readable on the shared path with no
        signal, so report them for manual removal rather than deleting
        something the wrapper does not own.
        """
        neutral = self.home / ".agents" / "skills"
        if not neutral.is_dir():
            return []
        wanted = set(neutral_union(self.repo))
        managed = set(self.state.get("neutral_skills", []))
        return sorted(
            entry.name
            for entry in neutral.iterdir()
            if entry.name not in wanted and entry.name not in managed
        )

    def doctor_checks(self, env: dict) -> list[tuple[str, tuple[bool | None, str]]]:
        checks: list[tuple[str, tuple[bool | None, str]]] = []
        drift = self.neutral_drift()
        substituted = self.neutral_identity()
        untracked = self.neutral_untracked()
        if drift or untracked or substituted:
            parts = []
            if drift:
                parts.append(f"managed, removed on next apply: {', '.join(drift)}")
            if untracked:
                parts.append(
                    f"untracked (pre-§4.1 mirror), remove manually: "
                    f"{', '.join(untracked)}"
                )
            if substituted:
                # The one that fails silently: the name is wanted, so drift
                # and untracked both skip it, and three harnesses load a copy
                # this repository did not author (#93).
                parts.append(
                    f"not our copy, deployed under a managed name: "
                    f"{', '.join(substituted)}"
                )
            message = "~/.agents/skills — " + "; ".join(parts)
        else:
            message = "~/.agents/skills matches the neutral roster"
        checks.append(
            (
                "neutral-roster-drift",
                (not (drift or untracked or substituted), message),
            )
        )
        checks.append(
            ("apm-cli", (shutil.which("apm") is not None, "apm on PATH"))
        )
        checks.append(
            (
                "cowork-pin",
                (
                    bool(env.get("APM_COPILOT_COWORK_SKILLS_DIR")) or None,
                    "APM_COPILOT_COWORK_SKILLS_DIR (needed with multiple OneDrive mounts)",
                ),
            )
        )
        vault = env.get("AGENT_MEMORY_VAULT")
        if not vault:
            checks.append(
                ("memory-vault-personal", (None, "AGENT_MEMORY_VAULT not set (M4)"))
            )
        elif is_corporate_mount(vault):
            checks.append(
                (
                    "memory-vault-personal",
                    (False, f"memory vault on a corporate mount: {vault}"),
                )
            )
        elif not Path(vault).is_dir():
            checks.append(
                (
                    "memory-vault-personal",
                    (False, f"memory vault path does not exist: {vault}"),
                )
            )
        else:
            checks.append(("memory-vault-personal", (True, vault)))
        fragment_file = self.mcp_fragment_file()
        if fragment_file.is_file():
            text = fragment_file.read_text(encoding="utf-8")
            for var in sorted(set(re.findall(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", text))):
                if env.get(var):
                    checks.append((f"mcp-env-{var}", (True, f"{var} set")))
                else:
                    checks.append(
                        (
                            f"mcp-env-{var}",
                            (
                                None,
                                f"{var} referenced by settings/mcp/servers.json"
                                " but not set",
                            ),
                        )
                    )
        for harness, root in (
            ("claude", Path(".claude/CLAUDE.md")),
            ("codex", Path(".codex/AGENTS.md")),
            ("copilot", Path(".copilot/AGENTS.md")),
        ):
            root_file = self.home / root
            if not root_file.parent.is_dir():
                checks.append(
                    (f"{harness}-root-file", (None, f"{harness} not installed"))
                )
            else:
                checks.append(
                    (
                        f"{harness}-root-file",
                        (
                            root_file.is_file()
                            and APM_MARKER
                            in root_file.read_text(encoding="utf-8"),
                            str(root_file),
                        ),
                    )
                )
        return checks

    def doctor(self, env: dict) -> int:
        failed = 0
        for name, (ok, detail) in self.doctor_checks(env=env):
            if ok is True:
                print(f"[pass] {name}: {detail}")
            elif ok is None:
                print(f"[warn] {name}: {detail}")
            else:
                print(f"[FAIL] {name}: {detail}")
                failed += 1
        return 1 if failed else 0

    def remove(self, no_apm: bool = False) -> int:
        pi = self.state.get("pi_agents_md")
        if pi and Path(pi).is_file():
            text = Path(pi).read_text(encoding="utf-8")
            if SYNC_MARKER in text:
                Path(pi).unlink()
        self.state["pi_agents_md"] = None

        for live_path_str, previous in self.state.get("settings", {}).items():
            live_path = Path(live_path_str)
            if not live_path.is_file():
                continue
            live = json.loads(live_path.read_text(encoding="utf-8"))
            for key, value in previous.items():
                if value == ABSENT:
                    live.pop(key, None)
                else:
                    live[key] = value
            live_path.write_text(
                json.dumps(live, indent=2) + "\n", encoding="utf-8"
            )
        self.state["settings"] = {}

        for live_path_str, previous in self.state.get("mcp", {}).items():
            live_path = Path(live_path_str)
            if not live_path.is_file():
                continue
            live = json.loads(live_path.read_text(encoding="utf-8"))
            servers = live.get("mcpServers", {})
            for name, value in previous.items():
                if value == ABSENT:
                    servers.pop(name, None)
                else:
                    servers[name] = value
            live["mcpServers"] = servers
            live_path.write_text(
                json.dumps(live, indent=2) + "\n", encoding="utf-8"
            )
        self.state["mcp"] = {}

        codex_config = self.state.get("codex_mcp")
        if codex_config and Path(codex_config).is_file():
            path = Path(codex_config)
            path.write_text(
                self._strip_codex_block(path.read_text(encoding="utf-8")),
                encoding="utf-8",
            )
        self.state["codex_mcp"] = None

        for overlay_root in self.state.get("overlays") or []:
            path = Path(overlay_root)
            if path.is_file():
                path.write_text(
                    self._strip_overlay_block(path.read_text(encoding="utf-8")),
                    encoding="utf-8",
                )
        self.state["overlays"] = []

        codex_skills = self.state.get("codex_skills")
        if codex_skills and Path(codex_skills).is_file():
            path = Path(codex_skills)
            path.write_text(
                self._strip_codex_skills_block(path.read_text(encoding="utf-8")),
                encoding="utf-8",
            )
        self.state["codex_skills"] = None

        if not no_apm and self.state.get("repo"):
            subprocess.run(
                ["apm", "uninstall", "-g", self.state["repo"]], check=False
            )
        self.save_state()
        print("[ok] remove complete")
        return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["apply", "status", "doctor", "remove"])
    parser.add_argument(
        "--no-apm", action="store_true", help="skip apm install/uninstall"
    )
    args = parser.parse_args()

    import os

    syncer = Sync(repo_root=Path(__file__).resolve().parents[1])
    if args.command == "apply":
        return syncer.apply(no_apm=args.no_apm)
    if args.command == "status":
        return syncer.status()
    if args.command == "doctor":
        return syncer.doctor(env=dict(os.environ))
    return syncer.remove(no_apm=args.no_apm)


if __name__ == "__main__":
    sys.exit(main())
