#!/usr/bin/env python3
"""agent-dotfiles sync wrapper — everything APM does not own (SPEC §7).

Commands:
  apply   preflight -> apm install -g -> teardown -> Pi projection ->
          settings merges -> mcp merge -> state file
  status  report managed surfaces vs recorded state
  doctor  environment checks (CLIs, env vars, root-file ownership)
  remove  reverse everything recorded in state

Python 3 stdlib only. Idempotent throughout.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

APM_MARKER = "Generated by APM CLI"
SYNC_MARKER = "<!-- Generated by agent-dotfiles sync; edits will be overwritten -->"
ABSENT = "__ABSENT__"
CODEX_MCP_BEGIN = "# >>> agent-dotfiles mcp (managed; do not edit) >>>"
CODEX_MCP_END = "# <<< agent-dotfiles mcp <<<"

# Harnesses whose root files the dotfiles intentionally manage.
MANAGED_ROOT_FILES = (
    Path(".claude/CLAUDE.md"),
    Path(".codex/AGENTS.md"),
    Path(".copilot/AGENTS.md"),
)

# Root files APM's global compile writes for harnesses Jon does not use
# (live-trial wart 3). Removed on apply iff APM-marker-owned.
UNUSED_ROOT_FILES = (
    Path(".cursor/AGENTS.md"),
    Path(".kiro/AGENTS.md"),
    Path(".hermes/AGENTS.md"),
    Path(".config/opencode/AGENTS.md"),
    Path(".codeium/windsurf/AGENTS.md"),
    Path(".gemini/GEMINI.md"),
    Path(".gemini/antigravity-cli/AGENTS.md"),
)

CORPORATE_MOUNT_HINTS = ("OneDrive-SharedLibraries",)


def is_corporate_mount(path: str) -> bool:
    if any(hint in path for hint in CORPORATE_MOUNT_HINTS):
        return True
    for part in Path(path).parts:
        if part.startswith("OneDrive-") and part != "OneDrive-Personal":
            return True
    return False


def strip_frontmatter(text: str) -> str:
    lines = text.splitlines()
    if lines and lines[0] == "---":
        try:
            closing = lines.index("---", 1)
            return "\n".join(lines[closing + 1 :]).lstrip("\n")
        except ValueError:
            pass
    return text


def deep_merge(base: dict, patch: dict) -> dict:
    out = dict(base)
    for key, value in patch.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = deep_merge(out[key], value)
        else:
            out[key] = value
    return out


def load_default_skills(repo: Path) -> list[str]:
    roster = repo / "settings" / "default-skills.txt"
    return [
        line.strip()
        for line in roster.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


class Sync:
    def __init__(self, repo_root: Path, home: Path | None = None) -> None:
        self.repo = Path(repo_root)
        self.home = Path(home) if home else Path.home()
        self.runner = subprocess.run
        self.state_file = self.home / ".agent-dotfiles" / "state.json"
        self.state = self._load_state()

    # -- state ------------------------------------------------------------

    def _load_state(self) -> dict:
        if self.state_file.is_file():
            return json.loads(self.state_file.read_text(encoding="utf-8"))
        return {
            "version": 1,
            "settings": {},
            "mcp": {},
            "pi_agents_md": None,
            "removed": [],
        }

    def save_state(self) -> None:
        self.state_file.parent.mkdir(parents=True, exist_ok=True)
        self.state_file.write_text(
            json.dumps(self.state, indent=2) + "\n", encoding="utf-8"
        )

    # -- pi projection ----------------------------------------------------

    def pi_available(self) -> bool:
        return shutil.which("pi") is not None

    def project_pi(self) -> Path | None:
        pi_dir = self.home / ".pi" / "agent"
        if not pi_dir.is_dir():
            # pi installed but never launched (fresh machine): initialize
            if self.pi_available():
                pi_dir.mkdir(parents=True, exist_ok=True)
            else:
                return None
        target = pi_dir / "AGENTS.md"
        if target.exists() and SYNC_MARKER not in target.read_text(encoding="utf-8"):
            print(f"[skip] hand-authored, not overwriting: {target}")
            return None

        core = strip_frontmatter(
            (self.repo / "instructions" / "global.instructions.md").read_text(
                encoding="utf-8"
            )
        )
        overlay = (self.repo / "instructions" / "overlays" / "pi.md").read_text(
            encoding="utf-8"
        )
        target.write_text(
            f"{SYNC_MARKER}\n\n{core.strip()}\n\n{overlay.strip()}\n",
            encoding="utf-8",
        )
        self.state["pi_agents_md"] = str(target)
        return target

    def ensure_neutral_skills(self) -> None:
        """APM's neutral-path (~/.agents/skills) targeting is unreliable on
        fresh machines; mirror claude-scope skills into it when empty so
        Pi/Codex/Copilot always see the canonical set."""
        neutral = self.home / ".agents" / "skills"
        claude_skills = self.home / ".claude" / "skills"
        if not claude_skills.is_dir():
            return
        neutral.mkdir(parents=True, exist_ok=True)
        for skill in sorted(claude_skills.iterdir()):
            target = neutral / skill.name
            if skill.is_dir() and not target.exists():
                target.symlink_to(skill)

    # -- teardown ---------------------------------------------------------

    def teardown_unused_root_files(self) -> list[Path]:
        removed: list[Path] = []
        for relative in UNUSED_ROOT_FILES:
            path = self.home / relative
            if path.is_file() and APM_MARKER in path.read_text(encoding="utf-8"):
                path.unlink()
                removed.append(path)
        self.state["removed"] = sorted(
            set(self.state.get("removed", [])) | {str(p) for p in removed}
        )
        return removed

    def detach_managed_root_files(self) -> dict[Path, str]:
        """Remove only APM-owned roots so compile cannot reuse stale output."""
        backups: dict[Path, str] = {}
        for relative in MANAGED_ROOT_FILES:
            path = self.home / relative
            if not path.is_file():
                continue
            text = path.read_text(encoding="utf-8")
            if APM_MARKER in text:
                backups[path] = text
                path.unlink()
        return backups

    @staticmethod
    def restore_root_files(backups: dict[Path, str]) -> None:
        for path, text in backups.items():
            if not path.exists():
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")

    # -- settings ---------------------------------------------------------

    def merge_settings(self, fragment_name: str, live_path: Path) -> None:
        fragment_file = self.repo / "settings" / fragment_name / "settings.json"
        if not fragment_file.is_file():
            return
        fragment = json.loads(fragment_file.read_text(encoding="utf-8"))
        if not fragment:
            return

        live = {}
        if live_path.is_file():
            live = json.loads(live_path.read_text(encoding="utf-8"))

        previous = self.state["settings"].setdefault(str(live_path), {})
        for key in fragment:
            if key not in previous:
                previous[key] = live.get(key, ABSENT)

        live_path.parent.mkdir(parents=True, exist_ok=True)
        live_path.write_text(
            json.dumps(deep_merge(live, fragment), indent=2) + "\n",
            encoding="utf-8",
        )

    # -- mcp --------------------------------------------------------------

    def mcp_fragment_file(self) -> Path:
        return self.repo / "settings" / "mcp" / "servers.json"

    def declared_mcp_servers(self) -> dict:
        fragment_file = self.mcp_fragment_file()
        if not fragment_file.is_file():
            return {}
        return json.loads(fragment_file.read_text(encoding="utf-8")).get(
            "mcpServers", {}
        )

    def _merge_mcp_json(self, live_path: Path) -> None:
        """Merge the declared servers into a JSON file with a top-level
        mcpServers key, recording previous values for reversal."""
        servers = self.declared_mcp_servers()
        if not servers:
            return
        live = {}
        if live_path.is_file():
            live = json.loads(live_path.read_text(encoding="utf-8"))

        previous = self.state.setdefault("mcp", {}).setdefault(str(live_path), {})
        live_servers = live.get("mcpServers", {})
        for name in servers:
            if name not in previous:
                previous[name] = live_servers.get(name, ABSENT)

        live["mcpServers"] = deep_merge(live_servers, servers)
        live_path.write_text(
            json.dumps(live, indent=2) + "\n", encoding="utf-8"
        )

    def merge_mcp(self) -> None:
        """Project the declared MCP set into Claude Code user scope
        (~/.claude.json). Pi gets none by design (SPEC §3.4)."""
        self._merge_mcp_json(self.home / ".claude.json")

    def merge_copilot_mcp(self) -> None:
        """Copilot CLI reads ~/.copilot/mcp-config.json (same mcpServers
        schema). Only projected when the harness directory exists."""
        if not (self.home / ".copilot").is_dir():
            return
        self._merge_mcp_json(self.home / ".copilot" / "mcp-config.json")

    @staticmethod
    def _strip_codex_block(text: str) -> str:
        pattern = re.compile(
            r"\n*" + re.escape(CODEX_MCP_BEGIN) + r".*?" + re.escape(CODEX_MCP_END) + r"\n?",
            re.S,
        )
        return pattern.sub("", text)

    def merge_codex_mcp(self) -> None:
        """Codex has no user-scope JSON MCP surface; render the declared
        servers as a marker-delimited block in ~/.codex/config.toml.
        Servers the user already defines outside the block are skipped."""
        config = self.home / ".codex" / "config.toml"
        if not config.parent.is_dir():
            return
        servers = self.declared_mcp_servers()
        text = config.read_text(encoding="utf-8") if config.is_file() else ""
        base = self._strip_codex_block(text)

        lines: list[str] = []
        for name, spec in servers.items():
            if f"[mcp_servers.{name}]" in base:
                print(f"[skip] codex mcp: {name} defined outside managed block")
                continue
            lines.append(f"[mcp_servers.{name}]")
            if "url" in spec:
                lines.append(f'url = "{spec["url"]}"')
            auth = spec.get("headers", {}).get("Authorization", "")
            match = re.fullmatch(r"Bearer \$\{(\w+)\}", auth)
            if match:
                lines.append(f'bearer_token_env_var = "{match.group(1)}"')
            lines.append("")

        if lines:
            block = "\n".join([CODEX_MCP_BEGIN, *lines[:-1], CODEX_MCP_END])
            new = (base.rstrip("\n") + "\n\n" + block + "\n").lstrip("\n")
            self.state["codex_mcp"] = str(config)
        else:
            new = base
        if new != text:
            config.write_text(new, encoding="utf-8")

    # -- commands ---------------------------------------------------------

    def apply(self, no_apm: bool = False) -> int:
        if not (self.repo / "apm.yml").is_file():
            print(f"ERROR: {self.repo} is not the agent-dotfiles repo")
            return 2
        # ensure the neutral user-scope skills path exists so APM
        # populates it even when no other harness is detected yet
        (self.home / ".agents" / "skills").mkdir(parents=True, exist_ok=True)
        if not no_apm:
            skill_args = [
                argument
                for skill in load_default_skills(self.repo)
                for argument in ("--skill", skill)
            ]
            result = self.runner(
                ["apm", "install", "-g", str(self.repo), *skill_args],
                check=False,
            )
            if result.returncode != 0:
                print("ERROR: apm install failed; aborting apply")
                return result.returncode
            # install does NOT reliably compile root files on fresh
            # machines (E16 failure 2026-07-13) — compile explicitly,
            # BEFORE teardown so stale unused-harness roots are removed.
            # Marker-owned managed roots are detached first: APM has also
            # reported "unchanged" for stale output after source edits (V8).
            root_backups = self.detach_managed_root_files()
            compile_result = self.runner(["apm", "compile", "-g"], check=False)
            if compile_result.returncode != 0:
                self.restore_root_files(root_backups)
                print("ERROR: apm compile failed; aborting apply")
                return compile_result.returncode
            # A detected harness should be regenerated. If APM skipped one,
            # preserve its last-known-good marker-owned root instead of
            # turning a refresh into accidental removal.
            self.restore_root_files(root_backups)
        self.ensure_neutral_skills()
        removed = self.teardown_unused_root_files()
        pi = self.project_pi()
        self.merge_settings("claude", self.home / ".claude" / "settings.json")
        self.merge_settings("pi", self.home / ".pi" / "agent" / "settings.json")
        if (self.home / ".copilot").is_dir():
            self.merge_settings(
                "copilot", self.home / ".copilot" / "settings.json"
            )
        self.merge_mcp()
        self.merge_codex_mcp()
        self.merge_copilot_mcp()
        self.state["repo"] = str(self.repo)
        self.save_state()
        print(f"[ok] apply complete (teardown: {len(removed)}, pi: {bool(pi)})")
        return 0

    def status(self) -> int:
        issues = 0
        for relative in MANAGED_ROOT_FILES:
            path = self.home / relative
            if not path.parent.is_dir():
                print(f"[skip] {path} (harness not installed)")
                continue
            if not path.is_file():
                print(f"[missing] {path}")
                issues += 1
            elif APM_MARKER not in path.read_text(encoding="utf-8"):
                print(f"[unmanaged] {path} (no APM marker)")
                issues += 1
            else:
                print(f"[ok] {path}")
        for relative in UNUSED_ROOT_FILES:
            path = self.home / relative
            if path.is_file() and APM_MARKER in path.read_text(encoding="utf-8"):
                print(f"[stale] {path} (marker-owned, unused harness)")
                issues += 1
        pi = self.state.get("pi_agents_md")
        if pi:
            print(f"[ok] {pi}" if Path(pi).is_file() else f"[missing] {pi}")
        declared = self.declared_mcp_servers()
        if declared:
            surfaces: list[tuple[str, set[str]]] = []
            claude_json = self.home / ".claude.json"
            if claude_json.is_file():
                names = set(
                    json.loads(claude_json.read_text(encoding="utf-8")).get(
                        "mcpServers", {}
                    )
                )
                surfaces.append(("claude", names))
            codex_toml = self.home / ".codex" / "config.toml"
            if codex_toml.parent.is_dir():
                text = (
                    codex_toml.read_text(encoding="utf-8")
                    if codex_toml.is_file()
                    else ""
                )
                names = {
                    n for n in declared if f"[mcp_servers.{n}]" in text
                }
                surfaces.append(("codex", names))
            copilot_json = self.home / ".copilot" / "mcp-config.json"
            if (self.home / ".copilot").is_dir():
                names = set()
                if copilot_json.is_file():
                    names = set(
                        json.loads(
                            copilot_json.read_text(encoding="utf-8")
                        ).get("mcpServers", {})
                    )
                surfaces.append(("copilot", names))
            for surface, present in surfaces:
                for name in sorted(declared):
                    if name in present:
                        print(f"[ok] mcp:{surface}:{name}")
                    else:
                        print(f"[missing] mcp:{surface}:{name} (declared, not projected)")
                        issues += 1
        print(f"{issues} issue(s)")
        return 1 if issues else 0

    def doctor_checks(self, env: dict) -> list[tuple[str, tuple[bool | None, str]]]:
        checks: list[tuple[str, tuple[bool | None, str]]] = []
        checks.append(
            ("apm-cli", (shutil.which("apm") is not None, "apm on PATH"))
        )
        checks.append(
            (
                "cowork-pin",
                (
                    bool(env.get("APM_COPILOT_COWORK_SKILLS_DIR")) or None,
                    "APM_COPILOT_COWORK_SKILLS_DIR (needed with multiple OneDrive mounts)",
                ),
            )
        )
        vault = env.get("AGENT_MEMORY_VAULT")
        if not vault:
            checks.append(
                ("memory-vault-personal", (None, "AGENT_MEMORY_VAULT not set (M4)"))
            )
        elif is_corporate_mount(vault):
            checks.append(
                (
                    "memory-vault-personal",
                    (False, f"memory vault on a corporate mount: {vault}"),
                )
            )
        elif not Path(vault).is_dir():
            checks.append(
                (
                    "memory-vault-personal",
                    (False, f"memory vault path does not exist: {vault}"),
                )
            )
        else:
            checks.append(("memory-vault-personal", (True, vault)))
        fragment_file = self.mcp_fragment_file()
        if fragment_file.is_file():
            text = fragment_file.read_text(encoding="utf-8")
            for var in sorted(set(re.findall(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", text))):
                if env.get(var):
                    checks.append((f"mcp-env-{var}", (True, f"{var} set")))
                else:
                    checks.append(
                        (
                            f"mcp-env-{var}",
                            (
                                None,
                                f"{var} referenced by settings/mcp/servers.json"
                                " but not set",
                            ),
                        )
                    )
        for harness, root in (
            ("claude", Path(".claude/CLAUDE.md")),
            ("codex", Path(".codex/AGENTS.md")),
            ("copilot", Path(".copilot/AGENTS.md")),
        ):
            root_file = self.home / root
            if not root_file.parent.is_dir():
                checks.append(
                    (f"{harness}-root-file", (None, f"{harness} not installed"))
                )
            else:
                checks.append(
                    (
                        f"{harness}-root-file",
                        (
                            root_file.is_file()
                            and APM_MARKER
                            in root_file.read_text(encoding="utf-8"),
                            str(root_file),
                        ),
                    )
                )
        return checks

    def doctor(self, env: dict) -> int:
        failed = 0
        for name, (ok, detail) in self.doctor_checks(env=env):
            if ok is True:
                print(f"[pass] {name}: {detail}")
            elif ok is None:
                print(f"[warn] {name}: {detail}")
            else:
                print(f"[FAIL] {name}: {detail}")
                failed += 1
        return 1 if failed else 0

    def remove(self, no_apm: bool = False) -> int:
        pi = self.state.get("pi_agents_md")
        if pi and Path(pi).is_file():
            text = Path(pi).read_text(encoding="utf-8")
            if SYNC_MARKER in text:
                Path(pi).unlink()
        self.state["pi_agents_md"] = None

        for live_path_str, previous in self.state.get("settings", {}).items():
            live_path = Path(live_path_str)
            if not live_path.is_file():
                continue
            live = json.loads(live_path.read_text(encoding="utf-8"))
            for key, value in previous.items():
                if value == ABSENT:
                    live.pop(key, None)
                else:
                    live[key] = value
            live_path.write_text(
                json.dumps(live, indent=2) + "\n", encoding="utf-8"
            )
        self.state["settings"] = {}

        for live_path_str, previous in self.state.get("mcp", {}).items():
            live_path = Path(live_path_str)
            if not live_path.is_file():
                continue
            live = json.loads(live_path.read_text(encoding="utf-8"))
            servers = live.get("mcpServers", {})
            for name, value in previous.items():
                if value == ABSENT:
                    servers.pop(name, None)
                else:
                    servers[name] = value
            live["mcpServers"] = servers
            live_path.write_text(
                json.dumps(live, indent=2) + "\n", encoding="utf-8"
            )
        self.state["mcp"] = {}

        codex_config = self.state.get("codex_mcp")
        if codex_config and Path(codex_config).is_file():
            path = Path(codex_config)
            path.write_text(
                self._strip_codex_block(path.read_text(encoding="utf-8")),
                encoding="utf-8",
            )
        self.state["codex_mcp"] = None

        if not no_apm and self.state.get("repo"):
            subprocess.run(
                ["apm", "uninstall", "-g", self.state["repo"]], check=False
            )
        self.save_state()
        print("[ok] remove complete")
        return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["apply", "status", "doctor", "remove"])
    parser.add_argument(
        "--no-apm", action="store_true", help="skip apm install/uninstall"
    )
    args = parser.parse_args()

    import os

    syncer = Sync(repo_root=Path(__file__).resolve().parents[1])
    if args.command == "apply":
        return syncer.apply(no_apm=args.no_apm)
    if args.command == "status":
        return syncer.status()
    if args.command == "doctor":
        return syncer.doctor(env=dict(os.environ))
    return syncer.remove(no_apm=args.no_apm)


if __name__ == "__main__":
    sys.exit(main())
